### ISSUE TITLE
Add rucio quota check before submitting in Rucio mode

### ISSUE THREAD

**Issue by dciangot** [dmwm/CRABServer#5977] opened 2019-11-06 15:06 UTC

**Comment by amaltaro** [comment] 2019-11-07 07:54
In case it helps, I started working on this PR:
https://github.com/dmwm/WMCore/pull/9394

Still some final tests/tuning to be made though.

**Comment by dciangot** [comment] 2019-11-07 08:59
@amaltaro I think that could be useful indeed

@belforte what do you think?

**Comment by belforte** [comment] 2019-11-07 13:51
thanks @amaltaro We will work to use what you provide

**Comment by belforte** [comment] 2020-11-04 17:29
duplicate of #6172

**Closed by belforte** 2020-11-04 17:29 UTC
Labels: RUCIO
