### ISSUE TITLE
Scheduler choosing review

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#4586] opened 2014-12-10 19:42 UTC
Needs to review scheduler choosing for a task. 
 a) Now it is not considering if scheduler is down and if we have scheduler in rest configuration, it still can be chosen as good. https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/297/1.html
 b) Now  for schedd choose we are asking how much memory machine has. Not free, but in TOTAL. Better to change this to FREE memory. https://github.com/dmwm/CRABServer/blob/15fe70079ef98af2f9e64e20cb4d73e1898478c6/src/python/HTCondorLocator.py#L37
 c) If we need to drain schedd, we have to take it from rest configuration, and let jobs to finish. This command can be used on scheduler: `condor_drain`, but in current situation it will not work, because CRABServer still can choose this scheduler as good for new jobs to go.

**Comment by mmascher** [comment] 2015-01-23 11:24
Hi, Justas and I discussed a little bit about how we select the schedulers for the submission, and how this could be improved. The problem right now is that the big PM schedd we added yesterday is not getting many jobs compared to the others.

In fact, the formula is just a wighted choice that, yes, it gives more tasks to schedulers with more memory, but it does not take into consideration Idle and Running jobs.

Justas and I came up with an improved formula and we detailing it here  https://docs.google.com/spreadsheets/d/1xS-VMsBu0Bd9DIZ5ksTVVJ4TePC0GUfKyuy6FlozyKg/edit?usp=sharing

There are two factors, one that takes into consideration the "free running slots in the schedd", and one for the idle jobs. I called them `RunningFactor` and `IdleFactor`in the spreadsheet. The running factor is a number between 0 and 1 and is big if the scheduler is not running many jobs. Then there is the `IdleFactor` (between 0 and 0.2) which counts the total of idle jobs in all the schedd, and is big if a schedd has few idle jobs. These numbers are then added up and normilized with the `Memory` of the scheduler as before.

This is just a proposal subjects to change and comments before we start with the implementation. Anyone? If there are no comments maybe Justas can try to remember to bring this up in the next meeting :)

**Comment by belforte** [comment] 2015-01-23 12:34
I think it is a bad idea.
And I said that after having entertained same concept myself for a while, so nothing personal.

Reason is that due to the way DAGMAN works the #run and #idle is kept low intentionally and gives no indication on how many more jobs are waiting in the local DAG's ready to be submitted as soon a schedd has some breathing space. If we wanted to optimize submission really looking at load on schedd, we should look at how big the tasks are (both submitted and the one we are trying to allocate), how much they progressed, etc. Besides IIUC currently you pick a destination schedd for a task before you do job splitting so do not know how heavy this task is going to be.
In the end, since how many jobs can run on a schedd is ultimately decided by its RAM, current algorithm can hardly be improved, at least on the steady state. If the problem is that a new schedd is not loaded fast enough with new work, I would simply remove some of the others from the rotation for a bit.

**Comment by mmascher** [comment] 2015-01-26 09:04
Hi Stefano,

point taken. I guess there is nothing to do here then. Closing the issue.

**Comment by mmascher** [comment] 2016-05-03 13:37
Reopening, at the meeting of the 3rd of May we agreed we should improve how schedd are set up.

**Comment by mmascher** [comment] 2016-05-10 12:42
Few random thoughts:

* machines are not all the same (unfortunately), can we do better than simple random to pick up the schedd?
* Notice that even if machines were the same, simply randomly picking up the schedd would not be enough: we cannot predict the load, not all the task/jobs are the same (e.g.: different job length, #jobs per task etc), and even if they were the same we cannot predict failures (jobs may land on a broken site)

IMHO we need two things:
1) limits on the schedds (e.g. number of runing jobs, max running dags, number of uploads, etc) that can be schedd configuration parameters and are based on the schedd HW (the powerful the machine, the greater are the limits). These limits should be set in such a way that machine does not die (it does not start swapping, network is not saturating etc)
2) a way to choose schedds that keeps in mind those limits and back off if a schedd is busy. IMHO things like memory usage, CPU usage, network usage should not be a fatctor here since limits from 1) should preserve them.

In the spirit "do not re-invent the wheel" let's see what is already around.

1) SCHEDD LIMITS
These are some parameters we are currently setting, we usually concentrate on MAX_JOBS_RUNNING and the MAX number of DAGs, but there are others:
(from 99)
MAX_JOBS_RUNNING = 10000
SCHEDD_MAX_FILE_DESCRIPTORS = 80000
SHARED_PORT_MAX_FILE_DESCRIPTORS = 80000
SHADOW_NOT_RESPONDING_TIMEOUT = 8*3600
JOB_IS_FINISHED_COUNT=50
START_SCHEDULER_UNIVERSE = (TotalSchedulerJobsRunning < 350) && ((ShadowsRunning is undefined) || (ShadowsRunning < .95*$(MAX_JOBS_RUNNING))) #MAX_DAGS
(from 80)
MAX_CONCURRENT_UPLOADS = 300
MAX_CONCURRENT_DOWNLOADS = 300
MAX_PENDING_STARTD_CONTACTS = 50
(from CRAB3)
MAX_POSTJOBS=20 #the name is different
MAX_PREJOBS=20 #the name is different
MAX_IDLE_PER_TASK=1000 #the name is different

(More here http://research.cs.wisc.edu/htcondor/manual/v8.5/3_3Configuration.html#SECTION004310000000000000000)

2) BACKING OFF
In the GWMS frontend already has a mechanism to blacklist a schedd (line 774 https://cdcvs.fnal.gov/redmine/projects/glideinwms/repository/revisions/master/entry/frontend/glideinFrontendElement.py#L774) if:

* 'TransferQueueNumUploading>TransferQueueMaxUploading*0.95'
* 'TotalRunningJobs + TotalSchedulerJobsRunning' > 'MaxJobsRunning*0.95'
* 'CurbMatchmaking' evaluates to true (quoted: A ClassAd expression evaluated by the condor_schedd in the context of the condor_schedd daemon's own ClassAd. While this expression evaluates to True, the condor_schedd will refrain from requesting more resources from a condor_negotiator. Defaults to False.)

(useful command to check the situation now is here[1])

I think all the three make sense, maybe there is more we can add something else from here: http://research.cs.wisc.edu/htcondor/manual/v8.5/3_3Configuration.html#SECTION004310000000000000000

There are also some classads set in the schedd configurartion file (see /etc/condor/config.d/95_cms_daemon_monitoring.config on a schedd)[2] that monitor schedd healthness. They are called IsOK, IsWarning, and IsCritical.

PROPOSAL
As explained the CRAB3 backing off is a different problem than setting the limits and preserve schedd health.

For backoff I would re-use the IsOk/IsWarning/IsCrirtical mechanism (maybe tweaking the expressions to consider the GWMS frontend logic). Naively we can pick up a schedd at random, check if it is ok, and submit. Hopefully when it reaches IsWarning it is still functioning and there is still room before it reaches IsCritical. More elaborated, get a number from the metrics and do a weighted random choiche among the schedds that are OK.

For the schedd limits I would keep concentrating on MAX_RUNNING and MAX_DAGS, and I would also add MAX_CONCURRENT_UPLOADS. IMHO we need to start understanding the relationship between these numbers (well, without the max) and the schedd usage (memory/cpu/networ/disk) before we come up with what we can use as maximum. But I'd say also the values and the threshold for IsOK needs to be monitored..


[1]
condor_status -schedd -af Name TransferQueueNumUploading 'TransferQueueMaxUploading*0.95' 'TotalRunningJobs + TotalSchedulerJobsRunning' 'MaxJobsRunning*0.95' CurbMatchmaking TotalIdleJobs

[2]
IsWarning = ( ( RecentDCPumpCycleSum - RecentDCSelectWaittime ) / ( RecentDCPumpCycleCount + 1 ) > 0.3 ) || ( RecentDaemonCoreDutyCycle > 0.95 ) || ( RecentJobsExited > 2500 ) || ( TotalJobAds - TotalIdleJobs - TotalHeldJobs - TotalRunningJobs - TotalSchedulerJobsIdle > 500 ) || ( TotalRunningJobs - TotalLocalJobsRunning - TotalSchedulerJobsRunning - ShadowsRunning > 500 ) || ( FileTransferFileReadLoad_5m > 1.0 ) || ( FileTransferFileWriteLoad_1m > 1.0 ) || ( Autoclusters > 1500 )
IsOK =  !IsWarning &&  !IsCritical
IsCritical = ( ( RecentDCPumpCycleSum - RecentDCSelectWaittime ) / ( RecentDCPumpCycleCount + 1 ) > 0.5 ) || ( RecentDaemonCoreDutyCycle > 0.98 ) || ( RecentJobsExited > 3000 ) || ( TotalJobAds - TotalIdleJobs - TotalHeldJobs - TotalRunningJobs - TotalSchedulerJobsIdle > 1000 ) || ( TotalRunningJobs - TotalLocalJobsRunning - TotalSchedulerJobsRunning - ShadowsRunning > 1000 ) || ( FileTransferFileReadLoad_5m > 2.0 ) || ( FileTransferFileWriteLoad_1m > 2.0 ) || ( Autoclusters > 2000 )

**Comment by mmascher** [comment] 2016-05-11 18:27
Just to converge:

1) Not clear how to proceed on setting the MaxRunningJobs/MaxDags/MaxUploading limits, but I think we need to evaluate case by case empirically (slowly increase some numbers until schedd dies..).

2) For the backoff I have a first implementation proposal:
* Take as usual the list of the schedds
* filter out the ones that are !IsOk
* for each schedd calculate SCHEDD_CAPACITY(see below), and do a random choiche weighted with the SCHEDD_CAPACITY

SCHEDD_CAPACITY=1-Max(#JobsRunning/MaxRunning, #Dags/MaxDags, #Uploads/MaxUpploads)
The idea is that each one of the three terms inside the Max (let's call them metics) represent how close we are to a specific limit. We take the worst one, i.e., the one closer to the limit, and with 1- we get the reamining room/capacity for that. I am considering only these metrics since (for the moment) it seems they are the most important one (MaxUpploads and MaxRunning are also considered by the frontend). The formula can be extended with more metrics (at the meeting I was proposing to consider everything inside IsWarning/IsCritical maybe factoring /etc/condor/config.d/95_cms_daemon_monitoring.config in such a way that metrics were published, but it seemed an overkill).

Comments? I'd like to implement this ASAP since I think it can help to avoid reching the MaxRunning jobs in the schedd and have them ignored by the GWMS FE when sending pilots.

**Comment by belforte** [comment] 2016-05-11 20:29
why not include also UsedRam/totalRam ?
overall this looks sensible to me, and nothing wrong with trying, but I'd like to hear from @bbockelm as well
Main thing as usual is that when we do this we also need: a quick and clean way to change/roll-back, a way and a person to monitor things

**Comment by mmascher** [comment] 2016-05-12 03:15
Yeah, I thought about UsedRam/totalRam , but in principle it should not be neccessary: if MaxRunning and MaxDags are well tuned we should never exceed the ram in the system. I mean, if we start with memory, why not also cpu load/#cores, or a network related metric, diskIO etc? Let's configure condor so that the machine works and look what we put there as a configuration vs realnumbers.

**Comment by belforte** [comment] 2016-05-12 05:47
because in practice RAM usage is the best indicator we have of a schedd being in trouble. By the 
time RAM is critical may be too late to simply submit less, but that's a different story.

**Comment by mmascher** [comment] 2016-05-12 14:55
Ganglia memory usage is really stable and below the maximum now. At the moment we are not memory limited. But it's true we do not know in the future, and a schedd that starts swapping is lost and we should avoid that at any cost. Mine was more a "philosophical objection", but adding the memory to the metrics is not doing any bad, and maybe helps in some cases.

**Comment by bbockelm** [comment] 2016-05-12 19:12
The only concern I have with looking at UsedRam is that this is likely 15 minutes behind.  You always want to use it as a random weight - otherwise bursts of new tasks can end up all on one schedd.

If we incorporate that concern into the design, I'm OK with it.  We want to choose memory because it's the most scarce resource that we measure (if we have a good measure of IO in the ClassAd, we might alternately use that).

One thing to consider is avoiding a schedd if it is in warning or critical state.

**Comment by belforte** [comment] 2016-05-12 19:29
good point Brian. Yes. Marco already wrote about avoiding critical/warning schedd's.

**Closed** 2016-05-24 07:24 UTC
Labels: Condor, Support
