### ISSUE TITLE
failed transfers with 'no failure reason available'

### ISSUE THREAD

**Issue by dciangot** [dmwm/CRABServer#5498] opened 2017-05-31 08:19 UTC
Debugging this (https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/2926/1.html) I found a weird postJob (1) that I think can be the reason for the problem above, since on aso side I see this failed transfer (2) not followed by any pj and finishing after the last pj of the task ended reporting the transfer as succeeded(3).

So my impression here is that the postjob (1) tries to upload a new document in aso, but then, as it tries to check the status, it fails for unknown reasons. In this sense, it has submitted a transfer to aso, but then it lost track of it.
Does that make sense? Any idea? 

(1) https://cmsweb.cern.ch/scheddmon/0197/cms574/170528_205207:santocch_crab_MUONIA_G/postjob.1200.2.txt
https://pastebin.com/h18fj1BC
(2)
https://fts3.cern.ch:8449/fts3/ftsmon/#/job/804683ca-4486-11e7-a15f-02163e018998
(3)
https://fts3.cern.ch:8449/fts3/ftsmon/#/job/27505b84-4476-11e7-87ec-02163e018f23

**Comment by dciangot** [comment] 2017-05-31 09:41
I'm afraid that some synchronization problem is present in the postjob logic.

Here what I have understood so far:
-- on job resubmission, if the previous transfer failed, the postjob upload a new document on the transfer table with status new
-- if the upload succeeds start to check_transfers() (1)
-- so immediately  after the upload check for the transfer statuses (2). Here I still have to understand if the statuses are taken from the cached json or from Oracle, or both depending on the circumstances 
-- now, on the postjob discussed in this thread, the transfer appeared immediately as failed, making me think that is a cached status. Still can be an oracle cache or postjob json cache.
-- once the statuses are retrieved, the pj load doc by doc the failure reasons (3) for failed transfers got from above. But since it has just overwritten the file to put it in new, there are no failure messages to retrieve. So it exits with a failure, abbandoning the new file submitted to aso.

If I'm right, I think we need to take care of this with a pretty high priority.

(1) https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/PostJob.py#L465-L473

(2)
https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/PostJob.py#L366

(3)
https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/PostJob.py#L390

**Comment by belforte** [comment] 2017-05-31 12:24
better to upload the postjob log (seems short) before the schedd cleans things

**Comment by mmascher** [comment] 2017-05-31 12:35
I discussed this with Diego.

It seems there is a race candition and a check that we use to determine if we need to use or not the transfer status cachefile is not working (i.e.: another postjob updates the cache timestamp after we set the timestamp of the current upload, and before we check if we can safely use the cache).

We came to the conclusion that the PostJob should be deferred immediately after uploading the document to oracle. We were not doing that because previously transfers started on the WN. If we do not do that we always risk to use an outdated cache file (as it happened).

**Comment by belforte** [comment] 2017-05-31 13:05
seems a fragile solution to me. If you have a race, simply waiting will make things more rare, but not solve. 
Are you saying that the PJ updates oracle, then updates che cache, then reads the cache back but another process overwrote it in the meanwhile with a stale information ?
If that's the case, sounds like you need a robust lock.

**Comment by mmascher** [comment] 2017-05-31 13:31
In principle yes, but in this case the race condition is caused by the fact that the timestamp of the current upload is "younger" than the timestamp cache timestamp, which in turn happened before the oracle upload. By rerunning the postjob we will get a fresh "current upload timestamp" and the check will work.

**Comment by belforte** [comment] 2017-05-31 13:37
Locking machinery is already there. IMHO the problme is that writing to Oracle bypasses the cache. Instead PJ should lock the cache, write to oracle, update the cache, release the lock. In other workds, PJ should not udpate Oracle while another PJ has the lock on the cache. I understand that deferring the PJ will make it use the status 5 min later at which point the cache is expired and a fresh read should have been done with the new Oracle info, but there is no hard guarantee that this really happens.

**Comment by mmascher** [comment] 2017-05-31 13:39
Yeah, we can also lock the cachefile while updating oracle (even if we do not actually modify the file). It makes sense to me.

**Comment by belforte** [comment] 2017-05-31 13:49
yes, there's no point in checking xfer status one second after asking for the xfer. Unless we do not trust Oracle call exit code !
But now that we know that we have a potential race, let's make it rock solid :-)
I believe we have to modify the cache file before releasing the lock.  But I also think that I have not fully understood how those timestamps are used. So I may be making comments which do not apply. I guess the mechanism is documented by the code, right ?

**Comment by mmascher** [comment] 2017-05-31 14:34
On Wed, May 31, 2017 at 3:49 PM, Stefano Belforte <notifications@github.com>
wrote:

> yes, there's no point in checking xfer status one second after asking for
> the xfer. Unless we do not trust Oracle call exit code !
>
Ok good, so I guess the change can go in then.


> But now that we know that we have a potential race, let's make it rock
> solid :-)
> I believe we have to modify the cache file before releasing the lock. But
> I also think that I have not fully understood how those timestamps are
> used. So I may be making comments which do not apply. I guess the mechanism
> is documented by the code, right ?
>

Yeah, the code is a mess now, we should just rewrite the postjob getting
rid of couch code and all the code that assumes an injection is done from
the WN (including those timestamps). And maybe move the responsability of
creating the cache to the task process..

We are actually not locking the cache file but saving it to a tmp and then
moving it to the expected place..

**Comment by belforte** [comment] 2017-05-31 14:43
but you also do
  with getLock('get_transfers_statuses'):

but I agree that we can't spend days on this now. It would be great if at some
point someone has a week to rewrite the PJ as you indicated and clean things.

**Comment by belforte** [comment] 2017-05-31 14:53
a comment I wrote a couple hours ago and was in github limbo:
one line I do not understand in that PJ log:
```
Mon, 29 May 2017 15:34:25 CEST(+0000):INFO:PostJob Skipping logs archive file metadata upload, because it is marked as having been uploaded already from the worker node.
```
AFAIK nothing is uploaded from WN anymore. Is this a leftover from Couch era ?

**Comment by belforte** [comment] 2017-05-31 14:55
from The Zen of Python [1]
  If the implementation is hard to explain, it's a bad idea.
  If the implementation is easy to explain, it may be a good idea.

[1]
http://legacy.python.org/dev/peps/pep-0020/

**Comment by mmascher** [comment] 2017-05-31 15:00
On Wed, May 31, 2017 at 4:43 PM, Stefano Belforte <notifications@github.com>
wrote:

> but you also do
> with getLock('get_transfers_statuses'):
>

ops, I missed that, I added a lock.

**Comment by mmascher** [comment] 2017-05-31 15:04
Filemetadata were not involved at all when we developed ASO&Oracle, but I
do agree we should upload them in the PJ.

**Comment by belforte** [comment] 2017-05-31 15:12
ok about filemetadata, thanks for clarifying. About the lock... i fear I am confusing you. But there's not much point in having that lock if we do not update the cache. Concurrent writes (to different DB rows hopefully) are handled in Oracle. Anyhow. this was a rare problem, more rare now. Let's not add fix upon fix but in case streamlie the whole PJ.

**Closed** 2017-05-31 15:49 UTC
Labels: bug, Critical
