### ISSUE TITLE
LHE with more than 3 input files: remove warning for new CMSSW version

### ISSUE THREAD

**Issue by AndresTanasijczuk** [dmwm/CRABServer#4659] opened 2015-02-09 08:47 UTC
See https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/393.html
I reproduced the problem using users original pset and crab config.

**Comment by mmascher** [comment] 2015-02-18 14:55
Hi @matz-e news about that?

**Comment by matz-e** [comment] 2015-02-18 15:00
Still waiting on feedback from CMSSW.  I could reproduce the job issue by taking the config and skipping more events than were in the first three files…

**Comment by mmascher** [comment] 2015-02-18 18:46
Thanks! But just to understand, will all the CMSSW version < CMSSW_something suffer of this bug?

**Comment by matz-e** [comment] 2015-02-18 19:40
If this really is a CMSSW issue, then yes.

**Comment by matz-e** [comment] 2015-02-26 11:49
To quote the [TWiki](https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideLHEInterface):

>  It is currently not recommended to use more than one input file at a time, because it has not been extensively tested. 

So until this is fixed in all CMSSW versions, users should keep to this recommendation.

**Comment by AndresTanasijczuk** [comment] 2015-02-26 12:22
Do I interpret correctly that this means that in the CMSSW pset there should not be more that 1 source LHE file?

**Comment by matz-e** [comment] 2015-02-26 13:01
Sort of.  It's a TWiki, so I don't know how up to date this is.  But as it says there, more than one LHE files have not been tested.  I just pinged some folks about my framework PR, I'd still like to hear what their opinion is.

**Comment by AndresTanasijczuk** [comment] 2015-02-26 13:45
I added a note in the tutorial about this: https://twiki.cern.ch/twiki/bin/view/CMSPublic/WorkBookCRAB3Tutorial#Running_MC_generation_on_LHE_fil

**Comment by mmascher** [comment] 2015-02-26 16:16
Is there anything else we should/could do on the CRAB3 side about this? Maybe check the pset and print a warning if more than one LHE file is present? I am just trying to see if we can close the ticket.

**Comment by belforte** [comment] 2015-02-26 16:48
but if it is a CMSSW issue, can only mean "at most one LHE file per job"
Not "one LHE file per task".

**Comment by annawoodard** [comment] 2015-02-26 17:30
Agreed, Stephano.

I think we can further clarify the documentation and possibly add a requirement in the code that users with more than one input LHE file use filebased splitting with number of units per job set to 1. I've verified that this works as expected.

**Comment by belforte** [comment] 2015-02-26 17:38
@annawoodard that would be perfect
@AndresTanasijczuk didn't we agree that Tutorial should be a reference manual ? By there is no hope that people will notice the small notes at the end of the section. Hopefully the code change that Anna indicated will make that note not-needed.

**Comment by matz-e** [comment] 2015-02-26 17:54
I wouldn't add more code in crab, though, if we can get this fixed in CMSSW.  A note in the documentation should probably be enough (if the PR is approved, I think that there's a way that users could backport the fix to their CMSSW release areas easily)

**Comment by ericvaandering** [comment] 2015-02-26 17:56
I assume @belforte means the tutorial should NOT be a reference manual

**Comment by belforte** [comment] 2015-02-26 18:00
@ericvaandering YES. of course. Sorry some keystroke remained in my fingertips
@matz-e this is very dangerous, people will not know they have to retrofit their CMSSW release, if a special thing is needed then Crab should detect lack of it and spit an error. If that's complicated we should at least print a WARNING any time LHE is used.

**Comment by annawoodard** [comment] 2015-02-26 18:05
Note that in order to use file based splitting, I had to set my job-type to Analysis-- is there a reason we can't just allow for file based splitting with PrivateMC tasks that are reading LHE files?

@matz-e, even if this gets fixed in cmssw-- sorry if this is obvious, but I'd like to understand, why do LHE files need to be treated differently than any others? For example, we have a separate argument for lheInputFiles (Sorry for not just looking in the code, but it's faster to ask :) )

**Comment by matz-e** [comment] 2015-02-26 18:17
LHE files are not index(ed|able)… and you have some slightly different setup compared to pythia for event splitting.  I also think that if you are using the job-type `Analysis` you are potentially missing some things like the lumi section specification for event generation and all your jobs may have produced the same lumis?  If that's the case, accounting for further processing is hard…

**Comment by annawoodard** [comment] 2015-02-26 19:01
> LHE files are not index(ed|able)… 

But why do we need to index for file-based jobs?

> and you have some slightly different setup compared to pythia for event splitting. 

I am using pythia (after madgraph).

> I also think that if you are using the job-type Analysis you are potentially missing some things like the lumi section specification for event generation and all your jobs may have produced the same lumis? If that's the case, accounting for further processing is hard…

That's true. But I can imagine some solutions that don't sound that complicated: each job gets an incrementing lumisection (or run), rather than incrementing each X events. 

I stand corrected about "just telling the users to use file-based splitting." It looks like we have two options:
1. Wait for it to be fixed in CMSSW (and accept that running on LHEs via CRAB is going to be pretty difficult until then, as you can only have 3 input files / task.) Until then, add a simple error for users that have too many input files and tell them they need to either merge their own input files or split up their tasks. We could include a link to an LHE file merger script, I'll try and dig one up.
2. Update our code to allow for file-based splitting, for PrivateMC tasks with LHE inputs. 

I suspect the consensus will be for option 1, though for my particular workflow, option 2 is appealing.

**Comment by annawoodard** [comment] 2015-02-26 19:18
The only script I can find ships with madgraph. I'm not sure where the source is hosted.

https://gist.github.com/annawoodard/cc23e9bb05b350d3d56f

**Closed** 2015-08-04 12:17 UTC
Labels: Critical
