### ISSUE TITLE
Do not overflow jobs if last try failure is 8028

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#5210] opened 2016-04-27 07:28 UTC
~30%  of jobs which are overflowed to T2_US sites are failing from T1_US As you can see from the image, it has a lot of failures.

One dataset which is not accessible at all remotely (100% failure):
![image](https://cloud.githubusercontent.com/assets/646582/14844486/03ace47e-0c58-11e6-9a6f-231d13f1b41f.png)
Data is on FNAL and job runs elsewhere (30% failure):
![image](https://cloud.githubusercontent.com/assets/646582/14844562/81e1f91a-0c58-11e6-92b8-db07091358a6.png)

For example I took one task: http://dashb-cms-job.cern.ch/dashboard/templates/task-analysis/#user=default&refresh=0&table=Jobs&p=1&records=25&activemenu=2&status=&site=&tid=160425_215922%3Adburns_crab_bkg_Spring15_QCD_Pt_800to1000 and:

```
== CMSSW: 26-Apr-2016 22:37:02 PDT  Initiating request to open file /hadoop/cms/phedex/store/mc/RunIIFall15DR76/QCD_Pt_800to1000_TuneCUETP8M1_13TeV_pythia8/AODSIM/PU25nsData2015v1_76X_mcRun2_asymptotic_v12-v1/70000/F0B7651D-2B9F-E511-B727-00259073E504.root
== CMSSW: 26-Apr-2016 22:37:02 PDT  Fallback request to file root://cmsxrootd.fnal.gov//store/mc/RunIIFall15DR76/QCD_Pt_800to1000_TuneCUETP8M1_13TeV_pythia8/AODSIM/PU25nsData2015v1_76X_mcRun2_asymptotic_v12-v1/70000/F0B7651D-2B9F-E511-B727-00259073E504.root
== CMSSW: [2016-04-26 22:37:03.976467 -0700][Error  ][Utility           ] Unable to resolve cmsdcadisk01:1095: Name or service not known
== CMSSW: [2016-04-26 22:37:03.976591 -0700][Error  ][PostMaster        ] [cmsdcadisk01:1095 #0] Unable to resolve IP address for the host
```

This for sure shows site issue, but in the end CRAB3 could be smarter in this respect. If previous job failed with 8028, do not allow to overflow it with CMS_ALLOW_OVERFLOW = False
Why it is good to be a bit smarter:
a) Some users do not think or contact for help. I see some jobs are resubmitted up to 10 times and they end up the same.
b) Failed job runtime ~2minutes, which leads pilot to sleep ~18mins and this is not good as we discussed already. Success job runtime a bit more than 20mins.

What else we can do to improve:
Some improvements are coming to cms-gwmsmon to monitor efficiency and failures, same as runtime and memory usage. 
Another thing, there is no ticket to site, is there anyone following usual failures, monitoring them and reporting, if it is site issue?

**Comment by jmarra13** [comment] 2016-04-27 07:41
I got the same issue in one the validation Task[1], only the jobs landed on FNAL ran fine.

[1] http://dashb-cms-job.cern.ch/dashboard/templates/task-analysis/#user=Jadir+Marra+da+Silva&refresh=0&table=Jobs&p=1&records=-1&sorting%5B%5D=3&sorting%5B%5D=asc&activemenu=1&status=&site=&tid=160426_143109%3Ajmsilva_crab_HG1605a-1-Analysis_Use_Parent-L-T_O-T_P-T_IL-F-DOC-T

**Comment by belforte** [comment] 2016-05-02 10:29
This is an 'after the fact' solution. But is is not the way.

If we expect 8028 to be a glitch, we retry. If we are confident that xrootd failing means "no-way" we shoul call it fatal and not retry.
It has nothing to do with overflow. Those jobs could all have run at the same site, fail with 8028 and waste resources exactly the same way. That we run jobs bound to fail instead of keeping them in the idle queue is not a bug.
And user resubmitting blindly for weeks is a more general issue for which we have no good idea yet.

Unless I miss something, and you have much stronger arguments, let's close.

**Comment by juztas** [comment] 2016-05-02 11:13
'after the fact' can happen any time now or tomorrow or next week. Either you make things smart or ignore it. In respect of improving, crab3/schedds/aso can benefit from that.
For this specific case:
If data is on TX_US and your job ran on TY_US where data is not available and failed with 8028, it is worth to try not to overflow next retry (Does it hurt for you to do so?). For sure it can happen that also on same site where data is it will fail with same error, but you even tried to do that.
They can`t turn off SI overflow and it is good (they could with extraJDL) and if resubmitting, they end up on same sites. Also why it is not good is written here: https://github.com/dmwm/CRABServer/issues/5210#issue-151316957
Also question was not answered and just looking few simple cases, exitCodes there are places where to improve and bring data to the users faster.

**Comment by belforte** [comment] 2016-05-02 12:24
I meant that it is an ad-hoc solution for a specific situation
that will not work as well when you have same symptoms for a different reason.
Anyhow..
all that CRAB can do is to decide if to resubmit or not,
whether to overflow is a decision inside gWms.

You are saying that at times data that are expected to be available
via xrootd, in fact are not. That a situation that we can not
detect before it happens, nor can we predict when it will stop.
So CRAB must ignore it and let others deal with it.

If gWMS and xrootd becomes smart enought to optimize further the
overflow machinery, we'll be happy. But this is not a situation
where making CRAB logic more complex is worth.

Maybe you are finding cases where overflow should be temporarely
turned off for some sites, and it is not done. I am sure there are
such cases. But simple systems have great virtues, even if at
times reality is more complex and we fall short of full optimization.

**Comment by belforte** [comment] 2017-02-14 10:41
I stand by my old conclusion. There is no way to fix this in CRAB, other then calling 8028 fatal (i.e. if we decide that xrootd infrastructure is reliable enough that when it fails we have to wait tomorrow (i.e. user  resubmission)

**Closed** 2017-02-14 11:17 UTC
