### ISSUE TITLE
New crab status fails to report timed out jobs as failed 

### ISSUE THREAD

**Issue by dciangot** [dmwm/CRABServer#5487] opened 2017-05-12 14:17 UTC
This contribute to have "fake" publication failures, as in this case: https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/2876/1/1/1/1.html

And more over those jobs cannot resubmitted since they are in state "transferring" forever.

> [16:11 dciangot@lxplus012 crab_debug] > crab statusold crab_step1_nothdm_2p5TeV_76_DIGI2RAW
> Enter GRID pass phrase for this identity:
> Contacting lcg-voms2.cern.ch:15002 [/DC=ch/DC=cern/OU=computers/CN=lcg-voms2.cern.ch] "cms"...
> Remote VOMS server contacted succesfully.
> 
> 
> Created proxy in /tmp/x509up_u34086.
> 
> Your proxy is valid until Sat May 13 16:11:40 CEST 2017
> CRAB project directory:         /afs/cern.ch/work/d/dciangot/dir_CMSSW/CMSSW_7_0_5/src/MNTriggerStudies/MNTriggerAna/test/CSA14/crab_debug/crab_step1_nothdm_2p5TeV_76_DIGI2RAW
> Task name:                      170504_205652:sundleeb_crab_step1_nothdm_2p5TeV_76_DIGI2RAW
> Grid scheduler:                 crab3@vocms0197.cern.ch
> Task status:                    KILLED
> Task URL to use for HELP:       https://cmsweb.cern.ch/crabserver/ui/task/170504_205652%3Asundleeb_crab_step1_nothdm_2p5TeV_76_DIGI2RAW
> Dashboard monitoring URL:       http://dashb-cms-job.cern.ch/dashboard/templates/task-analysis/#user=sundleeb&table=Mains&pattern=170504_205652%3Asundleeb_crab_step1_nothdm_2p5TeV_76_DIGI2RAW
> 
> **Jobs status:                    failed          7.6% ( 19/250)**
>                                 finished       92.4% (231/250)
> 
> Publication status:             finished       92.4% (231/250)
>                                 failed          7.6% ( 19/250)
> 
> Output dataset:                 /NonThDM/sundleeb-step1_nothdm_2p5TeV_76_DIGI2RAW-19898e58c9c00509372f15bcc801ecbe/USER
> Output dataset DAS URL:         https://cmsweb.cern.ch/das/request?input=%2FNonThDM%2Fsundleeb-step1_nothdm_2p5TeV_76_DIGI2RAW-19898e58c9c00509372f15bcc801ecbe%2FUSER&instance=prod%2Fphys03
> 
> Error Summary: (use crab status --verboseErrors for details about the errors)
> 
>  19 jobs failed in postprocessing step
> 
> Have a look at https://twiki.cern.ch/twiki/bin/viewauth/CMSPublic/JobExitCodes for a description of the exit codes.
> Log file is /afs/cern.ch/work/d/dciangot/dir_CMSSW/CMSSW_7_0_5/src/MNTriggerStudies/MNTriggerAna/test/CSA14/crab_debug/crab_step1_nothdm_2p5TeV_76_DIGI2RAW/crab.log
> [16:11 dciangot@lxplus012 crab_debug] > crab status crab_step1_nothdm_2p5TeV_76_DIGI2RAW
> CRAB project directory:         /afs/cern.ch/work/d/dciangot/dir_CMSSW/CMSSW_7_0_5/src/MNTriggerStudies/MNTriggerAna/test/CSA14/crab_debug/crab_step1_nothdm_2p5TeV_76_DIGI2RAW
> Task name:                      170504_205652:sundleeb_crab_step1_nothdm_2p5TeV_76_DIGI2RAW
> Grid scheduler:                 crab3@vocms0197.cern.ch
> Status on the CRAB server:      KILLED
> Task URL to use for HELP:       https://cmsweb.cern.ch/crabserver/ui/task/170504_205652%3Asundleeb_crab_step1_nothdm_2p5TeV_76_DIGI2RAW
> Dashboard monitoring URL:       http://dashb-cms-job.cern.ch/dashboard/templates/task-analysis/#user=sundleeb&refresh=0&table=Jobs&p=1&records=25&activemenu=2&status=&site=&tid=170504_205652%3Asundleeb_crab_step1_nothdm_2p5TeV_76_DIGI2RAW
> Status on the scheduler:        SUBMITTED
> 
> Jobs status:                    finished       92.4% (231/250)
>                                 **transferring    7.6% ( 19/250)**
> 
> Publication status:             done           92.4% (231/250)
>                                 failed          7.6% ( 19/250)
> 
> Output dataset:                 /NonThDM/sundleeb-step1_nothdm_2p5TeV_76_DIGI2RAW-19898e58c9c00509372f15bcc801ecbe/USER
> Output dataset DAS URL:         https://cmsweb.cern.ch/das/request?input=%2FNonThDM%2Fsundleeb-step1_nothdm_2p5TeV_76_DIGI2RAW-19898e58c9c00509372f15bcc801ecbe%2FUSER&instance=prod%2Fphys03
> Log file is /afs/cern.ch/work/d/dciangot/dir_CMSSW/CMSSW_7_0_5/src/MNTriggerStudies/MNTriggerAna/test/CSA14/crab_debug/crab_step1_nothdm_2p5TeV_76_DIGI2RAW/crab.log

**Comment by emaszs** [comment] 2017-05-12 14:49
Task process exited early, we probably want to increase the wait time to 48 hours or something (it's 24 hours now), will have to check later. For the moment I reran the caching script and status should be up to date.

```
Dag status code: 5 Entered current status date: 2017/05/07 18:26:34 CEST
Dag has been in one of the final states for over 24 hours.
Caching the status one last time, removing the task_process/task_process_running file and exiting.                                                                                                  
```

**Comment by emaszs** [comment] 2017-05-24 15:46
We said during the last meeting that keeping this at 24 hours is fine, if it happens again I'll investigate, it's not entirely clear to me where the problem is and putting it to 48 hours seems too random to me.

**Comment by belforte** [comment] 2017-05-24 15:52
I believe this will be solved by step 5. in latest proposal on "getting task life time under control":
https://github.com/dmwm/CRABServer/issues/4681#issuecomment-302336451

I am still waiting for @emaszs and @mmascher (at least) to review that proposal. If we agree, we can then close this issue and rather open new ones for the needed changes to submission expressions.

**Comment by belforte** [comment] 2017-09-18 10:59
this was done, see #4681

**Closed by belforte** 2017-09-18 10:59 UTC
Labels: bug, Critical
