### ISSUE TITLE
T1_* is not allowed destination site

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#4950] opened 2015-08-17 05:59 UTC
http://vocms096.cern.ch/mon/cms1404/150812_142238:mgalanti_crab_test_150812_singlet/job_out.1.0.txt

**Comment by belforte** [comment] 2015-08-17 08:42
will be solved by solving Issue #4921 
but indeed there is likely a missing (or wrong) check that should be fixed

**Comment by belforte** [comment] 2015-08-17 08:59
tried to lookup the TW code to check the check on T1's, but the logic of resolvePFNs  for example of lines https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/DagmanCreator.py#L326-L328 defeats my capability to understand
Maybe part of this is due to some attempt to support that stage out location is indicate by users by a site name, not a phedex node name. That should be rather be fixed by removing much of the code and telling users to indicate a Phedex Node Name. 
Overall all the stageout related code there looks way too complicated than it ought to be. And I really can't understand why we use a ClassAd to indicate the list of sites where we do not accept stageout
https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/DagmanCreator.py#L80
Is this in preparation of some fancy real time rescheduling as destination SE becomes (not)available ?
Do we document anywhere (even with a comment in the code, I do not ask much) what's the purpose and semantic of all those CRAB_ custom classAds ?

**Comment by juztas** [comment] 2015-08-17 09:19
to not allow as dest site is to add these site names in rest configuration: https://github.com/dmwm/CRABServer/blob/301bf3ffef0ce8f2e2c99d52e6d03834dc5461ef/src/python/CRABInterface/RESTUserWorkflow.py#L165

**Comment by belforte** [comment] 2015-08-17 09:23
IMHO that's surely a flexibility that we do not need.

**Comment by belforte** [comment] 2015-08-17 09:29
And mostly we need to make it clear that destination is a Phedex Node Name, not a Site Name. The earlier this is enforced in the code, the better.

**Comment by mmascher** [comment] 2015-08-17 09:35
Hi Stefano,

the `CRAB_BlacklistT1` classad is something that is deprecated, it is always 0. It was a boolean flag to indicate we do not run jobs on T1. It was removed in many places but probably somethiing leaked.

I also think these three lines https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/DagmanCreator.py#L326-L328 can be removed now that we are specifying a PNN and not a sitename for the stageout location.

That said if we want to enable stageout to T1 (now they are blacklisted as Justas said) we need some testing..

**Comment by belforte** [comment] 2015-08-17 09:45
if T1 were really blacklisted, why the task pointed to in this Issue was trying to stageout at FNAL_Buffer ?
Either black list is not correct, or there is a bug. If the latter, better to rewrite then to fix IMHO.
In theory stage out to T1 is under site control, not Crab.

**Comment by mmascher** [comment] 2015-08-17 09:48
Yes, the problem is that at some point I changed the logic for ASO destinations (https://github.com/dmwm/CRABServer/pull/4833) bu I did not update the blacklist

**Comment by belforte** [comment] 2015-08-17 09:57
hmmm.. let's see if I can find my way around here.. if the blacklist is in the REST config, I guess you refer to
https://git.cern.ch/web/CRAB3ServerConfig.git/blob/HEAD:/cmsweb-rest-config.json#l19
so the thing is to change T1_DE_KIT to T1_DE_KIT* etc. ? (or something semantically equivalent, as long as documented)

**Comment by belforte** [comment] 2015-08-17 09:59
by the way T1_TW does not exist anymore.

**Comment by mmascher** [comment] 2015-09-11 18:24
For the moment I fixed in http://git.cern.ch/pubweb/?p=CRAB3ServerConfig.git;a=blob_plain;f=cmsweb-rest-config.json the list od destinations adding _Disk . I should probably add _Buffer and _MSS as well but I figured it was easier to enable wildcards (see the commit above)

I will look at DagmanCreator now

**Comment by mmascher** [comment] 2015-09-11 18:32
I believe we can safely remove `_Disk` and `_MSS` as Stefano mentioned here https://github.com/dmwm/CRABServer/issues/4950#issuecomment-131736358

Removed in the commit above

**Closed** 2015-09-14 14:52 UTC
Labels: bug
