### ISSUE TITLE
consistently enforce a time limit for tasks

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#4681] opened 2015-02-24 08:33 UTC
```
2013731.0   cms017          2/1  11:11   0+00:18:43 I  20  3906.2 gWMS-CMSRunAnalysi
2014002.0   cms017          2/1  11:39   0+00:10:26 I  21  3906.2 gWMS-CMSRunAnalysi
```

```
[jbalcas@vocms0109 cluster2013728.proc0.subproc0]$ sudo voms-proxy-info -file de536849bfd16512fe8e528bee6913eb68b0e868
type      : RFC3820 compliant impersonation proxy
strength  : 1024
path      : /data/srv/glidecondor/condor_local/spool/3728/0/cluster2013728.proc0.subproc0/de536849bfd16512fe8e528bee6913eb68b0e868
timeleft  : 00:00:00

```

If proxy is expired on scheduler jobs will not run. We have to have possibility for users to update their proxy on scheduler and also these jobs should be removed or set as held.

**Comment by belforte** [comment] 2015-02-24 09:26
I disagree
> If proxy is expired on scheduler jobs will not run. We have to have possibility for users to update
> their proxy on scheduler and also these jobs should be removed or set as held.

when task is initially submitted users should be required to have a long enough
credential in myproxy, then it is up to Crab Server to renew the proxy on schedd.
Long enough = as long as we want to allow a task to stay in the system, which AFAIR
is two weeks. After that jobs are removed, task is purged and if something was not
completed, user will have to create a recovery task.
Could be three weeks of course, or 18 days, or whatever, but we need a limit.

**Comment by juztas** [comment] 2015-02-24 09:34
TaskWorker is already renewing proxy, depending on myproxy delegation, but situation is the following:
Site is down for 3 weeks, jobs are idle, proxy delegation expires, site is up, but jobs cannot run and they are sitting idle. 
```
After that jobs are removed, task is purged and if something was not completed, user will have to create a recovery task.
```
No, they are not, and they can stay idle months... I would put removal for jobs which proxy expired and as you say user will have to create a recovery task.

**Comment by belforte** [comment] 2015-02-24 10:40
let's rephrase the issue then as:
  consistently enforce a time limit for tasks
and then we can sort details like "can proxy expire before the task reached its end of life ?"
Surely we can't offer any guarantee that a task can resume successfully after staying idle for months !

**Comment by mmascher** [comment] 2015-02-24 12:57
Hi @juztas , do you know why the TW did not renew the proxy on the schedd?

**Comment by belforte** [comment] 2015-02-24 13:09
@mmascher Justas already explained that task sat on schedd more then 3 weeks, so the credential in myproxy expired.

**Comment by mmascher** [comment] 2015-02-24 13:47
Ah thanks Stefano, I missed that.  FWIW the user did not use CRAB3 for at least two weeks (or his cert was expiring), otherwise his proxy would have been renewed in CRAB3. Infact, proxies are delegated in myproxy for 30 days whenever a crab command is executed, and are renewed for other 30day if their lifetime in myproxy is <15 days.

The lifetime of a task is one month AFAIK, so maybe we should change the previous numbers to 45/30 for example.

**Comment by belforte** [comment] 2015-02-24 13:54
one month is a very long time if we e.g. want to do disruprive hw intervention.
Do we have any way to monitor what is the natural lifetime of tasks ?
Indeed you want to change to 45/30, even if we decide to cut tasks at 2 or 3 weeks
it will not harm to have longer-lived credentials. And verify what happens when the task
lifetime expires, i.e. clear and consistent notification to user, proper cleanup etc.
e.g. set a limit at 2 days in the test instance and see how it goes.

Rather the problem is to give users time to renew their certificate well before
crab fails because it can't get a 30-day credential in myproxy. It is only difficult
in the sense that it is difficult to send simple, clear, timely messages to users
which they can act upon w/o bugging us.

**Comment by belforte** [comment] 2015-03-30 15:14
From the Crab meeting on March 30:
somehow current situation/proposal is:
 - remove jobs idle for two weeks (guess they will never run and currently do not guarantee that credential in my proxy is valid for more then 2 weeks)
- hold the DAG after two weeks, up to a month, since user can still do a crab status or similar, and thus load a fresh credential on myproxy, then DAB can be released
There are two problems:
1. releasing the DAG requires a recovery procedure to find those jobs which we removed
2. in any case, if some jobs did not run for 2 weeks, chances they start running is slim at best
A different proposal is:
keep things simple, define one single lifetime (if 2 weeks is too low, make it 3, or 4). Then make sure that credential myproxy is good for that long, and N days after initial submission kill everything and wrap-up.

I vote for the simple and brutal solution.

**Comment by annawoodard** [comment] 2015-04-21 10:50
+1 for the simple and brutal solution.

**Comment by belforte** [comment] 2015-09-14 10:50
if @juztas agrees I will assign to myself so that I will be one charged with tracking this and opening small issues for the various steps

**Comment by belforte** [comment] 2016-05-02 10:35
I think we need to raise the priority of this, or it will never done, but we need it.
@mmascher do you feel like you can take care ?

**Comment by mmascher** [comment] 2016-05-02 10:50
Hi Stefano,

but I am not sure what are the action items here. I read the isse and it was focusing on user credentials lifetime. E.g.:  right now we keep the DAG for one month, we sent it with a one week long proxy and we (try to) renew the proxy. After one month the DAG is removed.

Is it still that what we are trying to solve (hence the action item is your brutal solution https://github.com/dmwm/CRABServer/issues/4681#issuecomment-87718441), or we came back to this because of other reasons?

**Comment by belforte** [comment] 2016-05-02 11:20
it is the brutal solution. Wrap up and cleanup. The problem of the day is that old instance of ASO is still dealing with resubmissions from a task 1.5 months old which has all the appearance of a user script gone beserk (kees resubmitting also succesful jobs !)
I want the freedom to turn off switches w/o bothering to check what's running

**Comment by mmascher** [comment] 2016-05-02 11:30
Oh, after one month the DAG should have been removed. What's the taskname? My policy is that we can forget a task after one month.

Sidenote, we keep the task in the task database because in principle =crab report= works and users can easily expand an old task (although I am not so sure it is still working..)

**Comment by belforte** [comment] 2016-05-02 12:52
this task:
https://cmsweb.cern.ch/crabserver/ui/task/160318_192308:ahart_crab_candidateTrackProducer_WToLNu
It is an odd situation, TaskInfo tab shows the DB entries, but Main tab shows nothing, yet jobs have been resubmitted up to Apr 30 and ran yesterday (see dashboard link)
even if TW log reports failure to contact schedd

I

**Comment by belforte** [comment] 2016-05-02 13:00
@mmascher even if the old DAG is removed... dosn't every resubmit create a new dag ?

**Comment by belforte** [comment] 2016-05-02 13:14
indeed
```
belforte@vocms0114/cluster5847513.proc0.subproc0> pwd
/data/srv/glidecondor/condor_local/spool/7513/0/cluster5847513.proc0.subproc0
belforte@vocms0114/cluster5847513.proc0.subproc0> ls -ltr *dag*
-rwxr-xr-x 1 cms825 zh       3164 Mar 18 21:01 dag_bootstrap.sh*
-rwxr-xr-x 1 cms825 zh       6951 Mar 18 21:01 dag_bootstrap_startup.sh*
-rw-r--r-- 1 cms825 zh     324708 Mar 27 22:15 RunJobs.dag.rescue001
-rw-r--r-- 1 cms825 zh        590 Mar 27 22:15 RunJobs.dag.metrics
-rw-r--r-- 1 cms825 zh   15336783 Apr 30 10:14 RunJobs.dag
-rw-r--r-- 1 cms825 zh        146 Apr 30 10:15 RunJobs.dag.lock
-rw-r--r-- 1 cms825 zh 3416563069 May  2 08:54 RunJobs.dag.dagman.out
-rw-r--r-- 1 cms825 zh  127211335 May  2 09:03 RunJobs.dag.nodes.log
belforte@vocms0114/cluster5847513.proc0.subproc0> 
```
I think you want to prevent the client from doing that after something like 3 weeks since initial submission.
Note that the spool directory for that task is full of files from March 18. We want a better cleanup !

**Comment by belforte** [comment] 2016-05-02 13:16
by the way, it is fine to keep the task longer in the DB for info etc., it is useful. But we should force the user to start a new task at some point. E.g. assume we wanted to retire or scratch over vocms0114, but it still manages old tasks. Of course we would do (as we did in the past) and user swallow the failures, but it is better to have a procedure.

**Comment by jmarra13** [comment] 2016-05-02 14:47
>Note that the spool directory for that task is full of files from March 18. We want a better cleanup !

The script used to clean the spool has the issue issue of the old one used for clean home dirs, it relies on condor_q to identify old tasks. I rewriting it using the same approach I used on this last one.

**Comment by mmascher** [comment] 2016-05-02 14:52
The current dag remove expression is "buggy"/uses a wrong logic: https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/DagmanSubmitter.py#L389

This causes a DAG node to be removed after 30 days it entered the "HELD" status, not after 30 days the task has been submitted.

Also, I noticed Farrukh turned on vocms099. This causes problems to old task because the collector HA does not kick in: if it was off we would contact the fnal collector, but since it is on and "empty" we contact it and simply do not find tasks.

**Comment by belforte** [comment] 2016-05-02 14:57
Is that really a bug, or a proper cleanup and the "remove task" is meant to be done by holding the DAG ? IIUC the user has no way to release the DAG, right ?
At some point I was lead to believe that all task end up in HELD, even if normally terminating.

I am not sure I fully understand the note about vocms099, is TW the only one who notices that vocms099 is empty ? Are you going to ping Farrukh ?

**Comment by mmascher** [comment] 2016-05-02 15:37
About 099 I pinged Farrukh and it has always been on. I was trying to understan why I saw `tm_task_failure	The CRAB server backend was not able to contact the Grid scheduler. Please try again later. If the error persists send an e-mail to hn-cms-computing-tools@cern.ch. Message from the scheduler: Unable to contact the collector and cached results are too old for using.` here https://cmsweb.cern.ch/crabserver/ui/task/160318_192308:ahart_crab_candidateTrackProducer_WToLNu . The collector of the task is 099 that has been retired, therefore the task is not found. I checked with Jadir and this was not happening right after the migration completed, maybe it's worth to check again now. It seems that we are starting to see failures now that the collector is empty and has no recollection of schedds... Anyway, that's not the place to discuss this :). I'll ping Farrukh and Jadir

About the other thing it's a bug if we said "let's enforce the 30 days limit". A `crab kill hold` a dag, and a `crab resubmit` releases it. The cleanup of the DAG is done by that classad. But it is not done after 30 days the task has been submitted, it is done 30 days after the task entered the status HOLD.

**Comment by belforte** [comment] 2017-01-01 20:37
This is still not clean. The stated goal was to keep a task for 30 dasy, then clean everything.
But this is not consistently done. Also we may want to reduce to 3 weeks and do not have a single point where to change this limit :-(
Let's list here all various actions that needs harmonizing:
1. crab resubmit is not allowd anymore after ?? days from initial submission
2. dagman is removed 30 days after initial submissions
3. spool directory is cleaned ...
4. web directory is cleaned ...
5. individual jobs are held/removed ...
6. credential  lifetime in myproxy is ...

more ?

**Comment by belforte** [comment] 2017-02-15 15:46
with reference to previous list https://github.com/dmwm/CRABServer/issues/4681#issuecomment-269918519
1. was done my Marco: resubmit not allowed after 3 weeks from initital submission
2. @todor-ivanov working on 2. 3. 4
  plan is to hold DAGMAN after 30 days but keep it in queue so that we see what happened and
   we can query condor for canceled DAG's to find directories to purge and then set LeaveInQueue to False
  Please Todor update this issue with progress
5. IIUC will be done by periodic_remove, @todor-ivanov please confirm

**Comment by belforte** [comment] 2017-02-15 18:38
leaving for me @belforte to verify number 6. i. e. myproxy credential need to be good for 1 month.
Have to decide what to do for users who wants to submit now and worry about renewing certificate next week.
We can certainly do the cleanup after 30 days anyhow and let things fail as proper when proxy expires. Only a matter of properly warning.

**Comment by belforte** [comment] 2017-02-15 19:11
What about task process ? @emaszs do we need to define and/or implement something ?

**Comment by emaszs** [comment] 2017-02-16 09:39
At the moment, task process exits after the dag enters a final state (so no more changes to the status are expected). It doesn't really matter for how long the task runs.

**Comment by belforte** [comment] 2017-04-11 16:41
Update: I wilk keep editing this as I fill the dots...
current understanding is:
1. task lifetime is set to 30 days [1]
2. crab resubmit is only allowed if at least 7 days are left in the lifetime [2]
3. dagman is removed from condor queue 40 days after initial submissions  [3]
4. spool directory is cleaned ...  [4]
5. web directory is cleaned ... [5]
6. individual jobs are held/removed ... [6]
7. credential  lifetime in myproxy is ... [7]
8. task process runs unitl ... [8]
references:
[1] https://github.com/dmwm/CRABServer/blob/master/src/python/ServerUtilities.py#L45
[2] https://github.com/dmwm/CRABServer/blob/master/src/python/ServerUtilities.py#L41-L47
[3] https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/DagmanSubmitter.py#L476-L480
[3]
[4]
[5]
[6]
[7]

**Comment by belforte** [comment] 2017-05-16 21:47
There is a problem with DAG's. Somehow at times they stay running wrongly assuming  that one node is still not done. e.g.
https://cms-logbook.cern.ch/elog/Analysis+Operations/1441
Which points out the fact that in the list above we do not have a step where we stop the DAG, and wait before cleaning up.

I think we should put a periodicHold expression after TASKLIFETIME from submission.

@mmascher @matz-e   what do you think ?

**Comment by belforte** [comment] 2017-05-16 22:11
P.S. I have seen other times this thing where a task waits for a node which is actually done, but never documented in the details that I did now.
I confess not having the sgtrength to collect all logs and make a problem report to condor devs.

**Comment by belforte** [comment] 2017-05-17 07:50
We keep saying that we hold the dagman, but we only issue condor_hold to the job which runs the dagman process, IIUC. I am notsure what exacly happens to the DAG when tha job is held/released.

**Comment by belforte** [comment] 2017-05-18 07:42
Details of the investigation on the "DAG still running after 39 days" are here:
https://cms-logbook.cern.ch/elog/Analysis+Operations/1452

Conclusion so far is that we do no know why the DAG thinks that one node is running while is not. I guess something not properly handled in crab kill/resubmit sequence. But I propose to live with that.
OTOH we need to make sure that new disk cleanup script (which takes list of tasks from condor_q ) runs before the jobs are removed from condor queue.
Concrete actions for DagSubmitter

1. set `leaveJobInQueue=True` 
2. set `periodicHold=(time()-crab_submissionTime>TASKLIFETIME)` or whatever is the correct HTC syntax for this

**Comment by belforte** [comment] 2017-05-18 08:26
TIme to write a new "final" plan, I guess:

1. we define TASKLIFETIME (30 days currently)
2. CRAB_TaskSubmitTime (TST) is set by TW in DagmanSubmitter.py and put in a classAd 
3. at TST+TASKLIFETIME - 7days we stop accepting crab resubmit
4. at TST+TASKLIFETIME - 2 days all idle jobs in schedd are removed by ???? (PeriodicRemove ?)
5. at TST+TASKLIFETIME DAG is put on Hold via PeriodicHold, TaskProcess keeps going, running jobs are removed (via PeriodicRemove?)
6. at TST+TASKLIFETIME + 2days TaskProcess stops
7. at TST+TASKLIFETIME + 8days DiskCleanup removes spool and web directories and removes task from condor queue (leaveJobInQueue=False)

Status:
- 1,  2 and 3: DONE (but may like to put TASKLIFETIME in a classAd as well)
- 4 and 5: to be done, will opne ad hoc issue
- 6 maybe done already, need to check with Emilis
- 7 ready to deploy in production, need to adjust to new times and classAds as defined here. will open adhoc issue

**Comment by belforte** [comment] 2017-05-18 08:35
@mmascher @emaszs can you please review the plan above and we converge at next meeting ? Here's a direct link:
https://github.com/dmwm/CRABServer/issues/4681#issuecomment-302336451

**Comment by belforte** [comment] 2017-05-18 08:40
hmm.. wouid it help that we defind an absolute time (secs from Epoch) as CRAB_TaskEndTime and put that in a classAd ? May make all periodic* and diskcleanup etc. code easier to read

**Comment by belforte** [comment] 2017-05-18 13:11
hmm.. wouid it help that we defind an absolute time (secs from Epoch) as CRAB_TaskEndTime and put that in a classAd ? May make all periodic* and diskcleanup etc. code easier to read

**Comment by emaszs** [comment] 2017-05-29 14:49
I have a few comments, though I'm also probably forgetting some details discussed in the past.

4. What's the reason behind this point? 2 days seems kind of random and meaningless though I'm sure there's a use for it.
6. Currently TP stops after the dag's `EnteredCurrentState` (final) becomes 1 day old. Since ASO timeouts take a day (plus whatever time the postjob needs to run), I guess it is foreseeable how 1 day would not always be enough for TP to fetch all of the changes in the logs before exiting. Indeed I think I should increase it to two days after all.

I guess I don't see anything else in the plan that makes me uncomfortable. TaskEndTime makes sense but we have to switch to it everywhere at once IMO, otherwise it'll just make things more confusing.

**Comment by belforte** [comment] 2017-05-30 13:14
about point 4., the idea was to prevent jobs from starting close to the `TaskEndTime` since they would be killed resulting in wasted resources and possibly more complex recovery. So I picked 2 days as the longest time we allow jobs to run. But did not take into account the ASO times. OTOH most jobs do not run that long. So 2 days seems a reasonably good time to have a very high chance that everything is done and properly wrapped up, including possibly a couple resubmission, at least for the average jobs.
And of course given that currently removed jobs are resubmitted by PostJob... it is not very clear how to do this.

Somehow there are 3 actions here:
 - stop accepting resubmission requests, i.e. stop adding jobs to the schedd queue
 - stop allowing new jobs to start
 - kill everything and close for good
It makes sense IMO to have different times. We can then tune the intervals.
By the way, now you make me think that maybe we want to stop the DAG from creating/resubmitting jobs at some time before the deadline. But I have no idea if there's a simply way to do this.

**Comment by belforte** [comment] 2017-06-08 13:52
In Crab meeting on May 30th , see https://indico.cern.ch/event/640918/note/
se decided to change point 4 to:
4. at TST+TASKLIFETIME  all  jobs in schedd are removed by PeriodicRemove

i.e. we allow max. possible time for things to run and when Lifetime expires, stop everything.

**Comment by belforte** [comment] 2017-06-08 15:51
will keep this open as a master ticket to track that all the sub-issues just opened are done

**Comment by belforte** [comment] 2017-09-29 11:44
all sub-issues have been done. We can finally close on this!

**Closed by belforte** 2017-09-29 11:44 UTC
Labels: Critical, enhancement
