### ISSUE TITLE
HG1509 Validation of 3.3.1509

### ISSUE THREAD

**Issue by mmascher** [dmwm/CRABServer#4954] opened 2015-08-18 11:32 UTC
Hi all,

here there is a list of things we are going to include in the Sptember release with the related checks I would like to perform.

Changes on the crabserver REST:
*    Fix pollution of backend urls (was causing the wrong collector to be propagated)
   * Make sure that submitting tasks specifying the ITB collector and schedd in the clien, and performing crab status on it, does not pollute successive submissions (new submissions use production collector/schedd). I have already tested it but worth double checking imho.
*    Improve error messages when we fail to curl the schedds
   * See for example  https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/861.html . Maybe we can turn off the http daemon on one schedd and see if we get this message. I have tested it raising the pycurl error in my code.
*    Add '()' to allowed SCRIPTARGS regexp
   * Not worth checking, I have already done the necessary tests
*    Retrieve publication failure reasons from ASO couch database in status API. It will require a change in an ASO couch view to work correctly
   * @AndresTanasijczuk , has ASO been deployed? Can be this tested `crab remake`ing a task that failed publication?
*    Add an API to the server to return the proxied url to contact schedds outside CERN
   * Configure the server as indicated here https://twiki.cern.ch/twiki/bin/view/CMSPublic/CMSCrabRESTInterface#External_dynamic_configuration and check that dashborards report the correct URL. Also I think this broke the `getlog --short` an I will need to fix it!
*    Improve the way we report transferred files
   * that's for tasks with multiple output when one output file failed the transfer. Not sure how to test this, maybe @AndresTanasijczuk has ideas

Changes on TaskWorker/PostJob/JobWrapper:
*    Postjob deferral
   * 
*    Get list of all dataset files from dbs, not only valid files. It will allow to run over INVALID and DEPRECATED datasets if necessary
   * Try to run over an INVALID and a DEPRECATED dataset and see if it works.
*    Truncate too long error messages to the TW (avoid tasks staying locked in QUEUED state)
   * Let's just reset tasks that were in QUEUED state after the deployment in September and keep an eye on them.
*    As usual improved error messages for the users and logs printouts
   * Nothing worth checking
*    Randomize injection loop in the taskworker to avoid only tasks in a certain status are processed
   * Nothing worth checking
*    Added the possibility to run 2 collectors on the same machine
   * That's more work on the schedd preparation side. I think 095 has a secondary collector running, but I am not sure we want to use it. Brian wanted to have one
*    Improved conditions to resubmit a job upon transfer failure
   * I have a memory lapsus, what was that?
*    Use proxied url in the dashboard taskmonitor page (logfiles will be accessible outside cern)
   * The test of this is included in the furs bullet
*    Fixed crab kill
   * Check if the kill works in different cases (jobs in different state). Send a big task and waits that transfer are being performed and postjobs are queued.
   * ok
*    Fixed dashboard reporting (jobids were wrong)
   * ok
*    Allow the usage of a secondary dataset.
   * ok
*    Do direct stageout if exeSite == storageSite
*    Sleep if job runtime is less than 20m
   * send a job that fails immediatly (wrong PSet?) and see if the walltime is 20mins. Check in the logs the sleep works
*    Allow the usage of a secondary dataset
   * @matz-e should document this first I guess
*    Force check of output stageout location in TaskWorker
   * Try to stageout to site where you do not have permission and verify the output. Also it would be nice to check what happens if gfal.copy fails (maybe writing a fake `gfal-copy-script`)
*    Sort task when getting them from the task db (priority to older tasks)
   * send many tasks and see if they gets submitted in the submission time order
*    InputFiles list is now defined inside a tarball
   * should be allright, but maybe we can varify that the same configuration that created an error works now? also maybe we can add a test for this

**Comment by AndresTanasijczuk** [comment] 2015-08-19 11:51
About testing the retrieval of publication failure reasons, I can see that the needed view is there in Couch testbed -not in prod- (https://cmsweb-testbed.cern.ch/couchdb/_utils/database.html?asynctransfer/_design/DBSPublisher/_view/PublicationFailedByWorkflow), but currently there is no workflow in Couch testbed with failed publications (actually, I see that all documents are in 'not_published' state). Causing a publication failure is hard I think. So maybe you can change by hand one document (change the publication_state to publication_failed and add a dummy publication_failure_reason) then do crab remake (remember to change the .requestcache file to point to preprod) and crab status.

**Comment by AndresTanasijczuk** [comment] 2015-08-19 12:03
About "Improve the way we report transferred files " for sure you must request to transfer more than 1 file per job (for example transfer output and log). But then you have to rely on that one of the files will be transferred quickly and the other slowly, so that when the quick transfer is done, crab status should still show the job state as 'transferring' instead of 'transferred', and only when all files in the job were transferred the state should change to 'transferred' (before it becomes 'finished'). I think it is hard to test without doing a hack somewhere (a possible hack would be to change a view in couch so that log files are not acquired for transfer; when I tested this in my private instance I think I hacked cmscp to do direct stageout for output files and local stageout for log files -or vice versa-).

**Comment by jmarra13** [comment] 2015-08-19 14:13
I try to run over a dataset(/MinBias/jmsilva-crab_scale_85065-3d12352c28d6995a3700097dc8082c04/USER) , previously set as DEPRECATED,  the dbs instance used was prod/phys03

And i got this error:
Task status:			FAILED
Warning:			The input dataset /MinBias/jmsilva-crab_scale_85065-3d12352c28d6995a3700097dc8082c04/USER is not 'VALID' but 'DEPRECATED'. CRAB will check if there are any valid files in the dataset and run only over those files. Please contact your physics group if you think the dataset should not be deprecated.
Error during task injection:	Problem handling 150819_140533:jmsilva_crab_HG1509-validation-runOverDeprecatedDS-02 because of 'NoneType' object has no attribute 'getFiles' failure, traceback follows
Traceback (most recent call last):
  File "/data/srv/TaskManager/3.3.1509.rc7/slc6_amd64_gcc481/cms/crabtaskworker/3.3.1509.rc7/lib/python2.6/site-packages/TaskWorker/Actions/Handler.py", line 82, in actionWork
    output = work.execute(nextinput, task=self._task)
  File "/data/srv/TaskManager/3.3.1509.rc7/slc6_amd64_gcc481/cms/crabtaskworker/3.3.1509.rc7/lib/python2.6/site-packages/TaskWorker/Actions/DBSDataDiscovery.py", line 143, in execute
    self.logger.debug("Got %s files" % len(result.result.getFiles()))
AttributeError: 'NoneType' object has no attribute 'getFiles'

**Comment by mmascher** [comment] 2015-08-19 14:27
Thanks Jadir, I will have a look at this.

Let me take the chance and pubblicize new monitoring: https://cmsweb-testbed.cern.ch/crabserver/ui/task/150819_140533:jmsilva_crab_HG1509-validation-runOverDeprecatedDS-02
I used it to check the TW logfiles.

**Comment by jmarra13** [comment] 2015-08-19 14:33
One more comment, if run over a dataset which is INVALID on dbs instance global the submission works, but if try to use one dataset on dbs instance phys03 it fails in the same way.

this one is phys03

Task name:			150819_142722:jmsilva_crab_HG1509-validation-runOverInvalidDS-02
Task status:			FAILED
Warning:			The input dataset /MinBias/jmsilva-crab_scale_70633-3d12352c28d6995a3700097dc8082c04/USER is not 'VALID' but 'INVALID'. CRAB will check if there are any valid files in the dataset and run only over those files.
Error during task injection:	Problem handling 150819_142722:jmsilva_crab_HG1509-validation-runOverInvalidDS-02 because of 'NoneType' object has no attribute 'getFiles' failure, traceback follows
Traceback (most recent call last):
  File "/data/srv/TaskManager/3.3.1509.rc7/slc6_amd64_gcc481/cms/crabtaskworker/3.3.1509.rc7/lib/python2.6/site-packages/TaskWorker/Actions/Handler.py", line 82, in actionWork
    output = work.execute(nextinput, task=self._task)
  File "/data/srv/TaskManager/3.3.1509.rc7/slc6_amd64_gcc481/cms/crabtaskworker/3.3.1509.rc7/lib/python2.6/site-packages/TaskWorker/Actions/DBSDataDiscovery.py", line 143, in execute
    self.logger.debug("Got %s files" % len(result.result.getFiles()))
AttributeError: 'NoneType' object has no attribute 'getFiles'


this one is global dbs:

Task name:			150819_130912:jmsilva_crab_HG1509-validation-runOverInvalidDS-01
Task status:			SUBMITTED
Warning:			The input dataset /GJets_HT-200To400_TuneCUETP8M1_13TeV-madgraphMLM-pythia8/RunIISpring15DR74-Asympt25ns_MCRUN2_74_V9-v1/MINIAODSIM is not 'VALID' but 'INVALID'. CRAB will check if there are any valid files in the dataset and run only over those files.
Glidemon monitoring URL:	http://glidemon.web.cern.ch/glidemon/jobs.php?taskname=150819_130912%3Ajmsilva_crab_HG1509-validation-runOverInvalidDS-01
Dashboard monitoring URL:	http://dashb-cms-job.cern.ch/dashboard/templates/task-analysis/#user=crab&refresh=0&table=Jobs&p=1&records=25&activemenu=2&status=&site=&tid=150819_130912%3Ajmsilva_crab_HG1509-validation-runOverInvalidDS-01
Details:			idle            8.3% ( 2/24)
				running        91.7% (22/24)

No publication information (publication has been disabled in the CRAB configuration file)
Log file is /afs/cern.ch/user/j/jmsilva/CRAB3-tutorial/CMSSW_7_0_5/src/HG1509Validation/validation/crab_HG1509-validation-runOverInvalidDS-01/crab.log

**Comment by belforte** [comment] 2015-08-19 15:35
how do you navigate from there to TW log ? I can't get anything. Maybe I am not authorized ?

> Let me take the chance and pubblicize new monitoring:
> https://cmsweb-testbed.cern.ch/crabserver/ui/task/150819_140533:jmsilva_crab_HG1509-validation-runOverDeprecatedDS-02
> I used it to check the TW logfiles.

**Comment by mmascher** [comment] 2015-08-19 15:46
Assuming you clicked on the "TaskWorker log" tab I would more look into a
javascript/browser compatibility issue. Or maybe even old javascript code
being cached (have you tried ctrl+r?). What browser/OS are you using? Any
chance you can give us some javascript console output (I use firebug to get
it)?

To rule out auth problem you can check this link:
https://cmsweb-testbed.cern.ch/crabcache/logfile?name=150819_140533:jmsilva_crab_HG1509-validation-runOverDeprecatedDS-02_TaskWorker.log&username=jmsilva

**Comment by belforte** [comment] 2015-08-19 15:49
tried again, and this time it worked. Let's ignore previous comment than. Thanks.

**Comment by mmascher** [comment] 2015-08-19 15:55
Hi Jadir,

phys03 or global does not matter, the problem is when a dataset that only
have invalid files. Before they were filtered out when we were calling the
DBS function to list files, now the filter is done in a successive step. I
fixed it in 8f54ec474331f01ff3306c7903b2ea0727598da9 . Maybe you can get
the updated file here and substitute [1]. I am marking down I need to
cherry-pick this commit for the prod release RPM.

[1]
https://raw.githubusercontent.com/dmwm/CRABServer/master/src/python/TaskWorker/Actions/DBSDataDiscovery.py

**Comment by belforte** [comment] 2015-08-19 15:57
but if a dataset has no valid files, I expect a message sayng that, not a
  AttributeError: 'NoneType' object has no attribute 'getFiles'

**Comment by mmascher** [comment] 2015-08-19 15:59
Yes, I have just fixed it in https://github.com/dmwm/CRABServer/commit/8f54ec474331f01ff3306c7903b2ea0727598da9#diff-7e09558b2c67dfe45ae3a3d1f371bfd9R151

**Comment by belforte** [comment] 2015-08-19 16:23
general comment on this "Validation" thing which looks a bit scary to me.

at times one has to judge how much effort is worth putting in dealing with corner cases,
expecially not reproducible ones.
As long things are not broken, even if improvement is not perfect, we can always test
code on an real case when it happens and see what to do.

A good code review may be another approach.

**Comment by jmarra13** [comment] 2015-08-20 09:09
Hi 

Now I invalidated one dataset without invalidate the files(to invalidate it I change this script[1] to not invalidate the files only the dataset) and run over it. 
 
Warning: Incompatible CRABClient version 3.3.1507
Server is saying that compatible versions are: ['3.3.11', '3.3.12', '3.3.13.rc4', '3.3.1509.rc7']
CRAB project directory:		/afs/cern.ch/user/j/jmsilva/CRAB3-tutorial/CMSSW_7_0_5/src/HG1509Validation/validation/crab_HG1509-validation-runOverInvalidDS-04
Task name:			150820_082228:jmsilva_crab_HG1509-validation-runOverInvalidDS-04
Task status:			COMPLETED
Warning:			The input dataset /GenericTTbar/jmsilva-CRAB3_jadir_MC_analysis_test1-37773c17ce2994cf16892d5f04945e41/USER is not 'VALID' but 'INVALID'. CRAB will check if there are any valid files in the dataset and run only over those files.
Glidemon monitoring URL:	http://glidemon.web.cern.ch/glidemon/jobs.php?taskname=150820_082228%3Ajmsilva_crab_HG1509-validation-runOverInvalidDS-04
Dashboard monitoring URL:	http://dashb-cms-job.cern.ch/dashboard/templates/task-analysis/#user=crab&refresh=0&table=Jobs&p=1&records=25&activemenu=2&status=&site=&tid=150820_082228%3Ajmsilva_crab_HG1509-validation-runOverInvalidDS-04
Details:			finished      100.0% (2/2)

No publication information (publication has been disabled in the CRAB configuration file)
Log file is /afs/cern.ch/user/j/jmsilva/CRAB3-tutorial/CMSSW_7_0_5/src/HG1509Validation/validation/crab_HG1509-validation-runOverInvalidDS-04/crab.log


[1] python ./slc6_amd64_gcc481/cms/dbs3-client/3.2.11d-comp3/examples/DBS3SetDatasetStatus.py -d /GenericTTbar/jmsilva-CRAB3_jadir_MC_analysis_test1-37773c17ce2994cf16892d5f04945e41/USER  -s INVALID -r False -u "https://cmsweb.cern.ch/dbs/prod/phys03/DBSWriter"

ps.: I overwrite DBSDataDiscovery.py with 8f54ec4

**Comment by mmascher** [comment] 2015-08-20 10:51
Thanks Jadir.

Hi Stefano, this might be too much, and maybe we can avoid to perform some of the tests I proposed and just monitor what happens in production. Keep in mind that the amount of load is doubled this time since we skipped a release, usually we have half of this work for the validation. Also, we might have some things already checked with the test suit we automatically perform for the validation.

But I think it is important to specifically check (by hand) what developers modified, and I am used to write down everything I would like to test. Then I let Justas(Jadir in this case) judge what is important to check, what can be skipped because we can just see how it goes in production, and what is already taken care with the test suit.

Re-reading it does not seems it's a too much work, but maybe I am underestimating it.

**Comment by juztas** [comment] 2015-08-20 11:02
My comments:
TEST: Fix pollution of backend urls (was causing the wrong collector to be propagated) 
TEST: Add an API to the server to return the proxied url to contact schedds outside CERN 
...
SKIP: Postjob deferral 
SKIP:Added the possibility to run 2 collectors on the same machine - `This is wrong. two schedds and it is already tested. No need to do anything`
TEST: Use proxied url in the dashboard taskmonitor page (logfiles will be accessible outside cern) 
TEST: Crab kill (specially dashboard report) `send 100 tasks, after that write loop which goes each directory and kills all tasks. jobs must be in all status`
SKIP: Sleep if job runtime is less than 20m - `In normal validation script, there is a test for this already which raises almost all possible failures`
TODO: Allow the usage of a secondary dataset - `We need validation template for this`
SKIP: Force check of output stageout location in TaskWorker -` There is also validation script.`
SKIP:InputFiles list is now defined inside a tarball - `For sure need to check!`

SKIP - means that normal validation script which are prepared, should test all this stuff. For sure we need to extend it and it is good to have (I think)

Also all possible crab client commands, for this would be good to have validation script.

**Comment by mmascher** [comment] 2015-08-20 11:10
And also test if the old client (the one we have in production now) works! That's something we always need to check

**Comment by juztas** [comment] 2015-08-20 11:11
we could make this validation script, which does all these commands

**Comment by jmarra13** [comment] 2015-08-20 13:26
for this 
TEST: Fix pollution of backend urls (was causing the wrong collector to be propagated) 

I ran a task[1] in one console using ITB collector and one ITB schedd and left a command running crab status on it, and in another console I sent 4 more tasks[2] to prod instance.

Every 3.0s: crab status validation/crab_HG1509-fixPolution-validation-04                                                                                                                                 Thu Aug 20 15:22:27 2015

[1] console one
Warning: Incompatible CRABClient version 3.3.1507
Server is saying that compatible versions are: ['3.3.11', '3.3.12', '3.3.13.rc4', '3.3.1509.rc7']
CRAB project directory:         /afs/cern.ch/user/j/jmsilva/CRAB3-tutorial/CMSSW_7_0_5/src/HG1509Validation/validation/crab_HG1509-fixPolution-validation-04
Task name:                      150820_125109:jmsilva_crab_HG1509-fixPolution-validation-04
Task status:                    SUBMITTED
Glidemon monitoring URL:        http://glidemon.web.cern.ch/glidemon/jobs.php?taskname=150820_125109%3Ajmsilva_crab_HG1509-fixPolution-validation-04
Dashboard monitoring URL:	http://dashb-cms-job.cern.ch/dashboard/templates/task-analysis/#user=crab&refresh=0&table=Jobs&p=1&records=25&activemenu=2&status=&site=&tid=150820_125109%3Ajmsilva_crab_HG1509-fixPolution-vali
dation-04
Details:                        finished       14.0% ( 7/50)
                                running         2.0% ( 1/50)
                                transferred    82.0% (41/50)
                                transferring    2.0% ( 1/50)

No publication information (publication has been disabled in the CRAB configuration file)
Log file is /afs/cern.ch/user/j/jmsilva/CRAB3-tutorial/CMSSW_7_0_5/src/HG1509Validation/validation/crab_HG1509-fixPolution-validation-04/crab.log

[2] console two
jmsilva@lxplus0082 ~/CRAB3-tutorial/CMSSW_7_0_5/src/HG1509Validation> for f in configs/testFixPollutionOfBackendUrls[3456].py;do crab submit $f;done
Will use CRAB configuration file configs/testFixPollutionOfBackendUrls3.py
Sending the request to the server
Success: Your task has been delivered to the CRAB3 server.
Task name: 150820_131122:jmsilva_crab_HG1509-fixPolution-validation4-04
Please use 'crab status' to check how the submission process proceeds.
Log file is /afs/cern.ch/user/j/jmsilva/CRAB3-tutorial/CMSSW_7_0_5/src/HG1509Validation/validation/crab_HG1509-fixPolution-validation4-04/crab.log
Will use CRAB configuration file configs/testFixPollutionOfBackendUrls4.py
Sending the request to the server
Success: Your task has been delivered to the CRAB3 server.
Task name: 150820_131135:jmsilva_crab_HG1509-fixPolution-validation5-04
Please use 'crab status' to check how the submission process proceeds.
Log file is /afs/cern.ch/user/j/jmsilva/CRAB3-tutorial/CMSSW_7_0_5/src/HG1509Validation/validation/crab_HG1509-fixPolution-validation5-04/crab.log
Will use CRAB configuration file configs/testFixPollutionOfBackendUrls5.py
Sending the request to the server
Success: Your task has been delivered to the CRAB3 server.
Task name: 150820_131148:jmsilva_crab_HG1509-fixPolution-validation6-04
Please use 'crab status' to check how the submission process proceeds.
Log file is /afs/cern.ch/user/j/jmsilva/CRAB3-tutorial/CMSSW_7_0_5/src/HG1509Validation/validation/crab_HG1509-fixPolution-validation6-04/crab.log
Will use CRAB configuration file configs/testFixPollutionOfBackendUrls6.py
Sending the request to the server
Success: Your task has been delivered to the CRAB3 server.
Task name: 150820_131203:jmsilva_crab_HG1509-fixPolution-validation7-04
Please use 'crab status' to check how the submission process proceeds.
Log file is /afs/cern.ch/user/j/jmsilva/CRAB3-tutorial/CMSSW_7_0_5/src/HG1509Validation/validation/crab_HG1509-fixPolution-validation7-04/crab.log

I don't know if this is the correct way to test this but seems that the first task does not cause any trouble in the subsequent tasks.

**Comment by jmarra13** [comment] 2015-08-20 13:35
The collector is the right one in all tasks

https://cmsweb-testbed.cern.ch/crabserver/ui/task/150820_131203:jmsilva_crab_HG1509-fixPolution-validation7-04
https://cmsweb-testbed.cern.ch/crabserver/ui/task/150820_131135:jmsilva_crab_HG1509-fixPolution-validation5-04
https://cmsweb-testbed.cern.ch/crabserver/ui/task/150820_131122:jmsilva_crab_HG1509-fixPolution-validation4-04
https://cmsweb-testbed.cern.ch/crabserver/ui/task/150820_131148:jmsilva_crab_HG1509-fixPolution-validation6-04

**Comment by mmascher** [comment] 2015-08-20 13:59
That should be allright, thanks!

**Comment by jmarra13** [comment] 2015-08-20 15:02
TEST: Use proxied url in the dashboard taskmonitor page (logfiles will be accessible outside cern) 
I used my own crabserver for this test with a modified rest configuration[1] 

http://dashb-cms-job.cern.ch/dashboard/templates/task-analysis/#user=crab&refresh=60&table=Jobs&p=1&records=-1&activemenu=0&status=&site=&tid=150820_144832%3Ajmsilva_crab_HG1509-ProxiedUrls-validation-04

dashboard is reporting proxied urls.

[1] https://gist.githubusercontent.com/jmarra13/19b1ad7d3658353560d6/raw/f2ee12e302d8243751bd4095abcba9fc826d5e0d/crab3jms2cfg.json

**Comment by jmarra13** [comment] 2015-08-21 09:03
TEST: Crab kill 

I submitted 100[1] tasks and after all submissions I start to kill all of them. lets see what will happen


[1] http://dashb-cms-job.cern.ch/dashboard/templates/task-analysis/#user=Jadir+Marra+da+Silva&refresh=0&table=Mains&p=1&records=100&sorting%5B%5D=7&sorting%5B%5D=desc&activemenu=0&pattern=*testCrabKill*&task=&from=&till=&timerange=lastDay

**Comment by jmarra13** [comment] 2015-08-21 10:24
All tasks were killed, but dashboard does not show them as killed. Is that right or expected?

**Comment by jmarra13** [comment] 2015-08-21 14:30
It's working, TW sent kill info to dashboard. 

http://dashb-cms-job.cern.ch/dashboard/templates/task-analysis/#user=Jadir+Marra+da+Silva&refresh=0&table=Mains&p=1&records=100&sorting%5B%5D=7&sorting%5B%5D=desc&activemenu=0&pattern=*testCrabKill-validation-04-*&task=&from=&till=&timerange=lastWeek

**Comment by AndresTanasijczuk** [comment] 2015-08-28 20:29
There is a bug in the PostJob: https://github.com/dmwm/CRABServer/blob/3.3.1509.rc8/src/python/TaskWorker/Actions/PostJob.py#L296 and https://github.com/dmwm/CRABServer/blob/3.3.1509.rc8/src/python/TaskWorker/Actions/PostJob.py#L309 should be specific to each post-job, i.e. the file name should contain the job number.

**Comment by AndresTanasijczuk** [comment] 2015-08-28 21:28
I just applied a patch https://github.com/AndresTanasijczuk/CRABServer/commit/b1974c16f86cf857d077f9cafd731832333107d0 for the above bug in the testbed TW.

**Comment by AndresTanasijczuk** [comment] 2015-08-28 22:56
Mhh, I only patched /data/srv/TaskManager/current/slc6_amd64_gcc481/cms/crabtaskworker/3.3.1509.rc8/lib/python2.6/site-packages/TaskWorker/Actions/PostJob.py but didn't recreate the tarballs in /data/srv/TaskManager/current/slc6_amd64_gcc481/cms/crabtaskworker/3.3.1509.rc8/data/
and I am not sure how to do it (why there is no script in /data/srv/TaskManager/ to do that?) Letting Justas, Jadir or Marco to do it.

**Comment by AndresTanasijczuk** [comment] 2015-08-29 19:37
I finally patched also the TaskManagerRun.tar.gz file today at ~20:00 and applied also this additional patch https://github.com/AndresTanasijczuk/CRABServer/commit/26c3aaa1e4fed0c862f7fed133525fbde35a245d
I ran a short test task to check these patches work, and they work ok. So now we have a manually patched TW 3.3.1509.rc8 in testbed.

**Comment by jmarra13** [comment] 2015-08-31 10:08
I was testing crab client commands and when I tested crab purge I got this error:

jmsilva@lxplus0000 ~/VALIDATE/test> crab purge --instance=preprod -d crab_HG1509h-4-Analysis_LumiBased_on_Data_BIG-L-T_O-T_P-T_IL-F
Warning: Incompatible CRABClient version 3.3.1509.rc5
Server is saying that compatible versions are: ['3.3.11', '3.3.12', '3.3.13.rc4', '3.3.1509.rc8']
Getting the tarball hash key
Checking task status
Task status: KILLED
Tarball hashkey: f945bac0879942ddbc0666227ef03d60822be92efd0f952e84c7a04856701d43
Attempting to remove task file from crab server cache
ERROR: TypeError: string indices must be integers, not str

	Please email hn-cms-computing-tools@cern.ch for support with the crab.log file or crab.log URL.
	Client Version: 3.3.1509.rc5
	The log file /afs/cern.ch/user/j/jmsilva/VALIDATE/test/crab_HG1509h-4-Analysis_LumiBased_on_Data_BIG-L-T_O-T_P-T_IL-F/crab.log has been uploaded automatically to the CRAB cache.
	Please email the following URL 'https://cmsweb.cern.ch/crabcache/logfile?name=2015-08-31_120251_crab.log&username=jmsilva' to hn-cms-computing-tools@cern.ch if you need help from Analysis Operations.

**Comment by jmarra13** [comment] 2015-08-31 11:48
I tested the following command with old client:

crab kill                                        OK
crab status                                  OK
crab submit                                  OK
crab tasks                                    OK
crab rmk                                       OK
crab uploadlog                             OK
crab report                                   OK
crab purge                                   OK

**Comment by belforte** [comment] 2015-09-11 11:21
IIUC crab 1509 is deployed now, can we then close this validation ?

**Comment by juztas** [comment] 2015-09-11 11:32
yes, can be closed. Almost all things for validation can be covered through script, but it is still missing few templates which has to be added (Mixing inputFiles). So can @jmarra13 take care of it?
a) add missing templates (mixing inputFiles)
b) add validation for deprecated, invalid dataset/files.
c) check crabclient commands on validation tasks (Also has to run with old client) with status/resubmit/getlog/output/checkwrite and etc...
d) We made this for production (https://github.com/juztas/scripts/blob/master/workload-checker.py) which I think Alan is using and similar thing could be done for crab.

Validation scripts help a lot to say green light for cmsweb deployment. (For me)

**Comment by belforte** [comment] 2015-09-11 11:37
I agree, but then, if OK with you, I'd put this list into a new Issue called "improve Crab validation scripts" and assign to @jmarra13

**Comment by juztas** [comment] 2015-09-11 11:37
Please, close it, creating new issue

**Comment by belforte** [comment] 2015-09-11 12:20
new issue is #4989

**Closed by belforte** 2015-09-11 12:20 UTC
