### ISSUE TITLE
Fix memory leaks in crabserver 

### ISSUE THREAD

**Issue by AndresTanasijczuk** [dmwm/CRABServer#5071] opened 2015-11-09 20:40 UTC
Diego said in the last release planning meeting that we should seriously consider to fix the memory leaks in the crabserver.

**Comment by juztas** [comment] 2015-11-09 20:59
I would suggest to include `mem_top` package, and in all API calls before return/raise do logging.debug("Memory leak %s : %s" % ("<NUMBER_TO_SEPARATE_AND_KNOW_THERE>", mem_top()))
Of course we would put some useless code, but that's the only way which can help a lot. On development/preprod not easy to see as we already tried with Jadir and left for ~12h running random crab commands and there was no leak.

**Comment by belforte** [comment] 2015-11-10 09:52
+1
what's the evidence we have of memory leak at the moment, i.e. how do they show up ?

**Comment by juztas** [comment] 2015-11-10 10:03
@geneguvo can you comment more? Where is this monitoring for memory usage per service ?

**Comment by geneguvo** [comment] 2015-11-10 10:23
https://meter.cern.ch/public/_plugin/kibana/#/dashboard/temp/CMS::CMSWEBDetailed

Filter by crabserver, then by any prod machine (i.e. vocms0136), set it to show "last 7days".
The rss+swap is only growing over time. The thing stays there on memory even when there's insignificant load on crabserver. On very busy crabserver days, it eats up all the rss+swap in less than 24h, so restarting it daily is not enough.

Also, we noticed that once the OS moves crabserver data to swap, it stays there forever even if we have lots of free ram space (i.e. freed by other applications). This is a sign that the stuff that has been swapped has not been claimed (accessed) anymore.

**Comment by geneguvo** [comment] 2015-11-10 13:23
Hi,
I've taken the memory dump of the crabserver in vocms0136 and put it on vocms22:/build/srv-state/core.7864. This is a 4GB dump.

It should be useful to find out what is in there. While quickly checking in with the "strings" command, I can clearly see there's a lot of json data in there.

I hope it will help finding the apis that are leaking.
Cheers,
Diego.

**Comment by geneguvo** [comment] 2015-11-10 13:23
I meant vocms022, not vocms22.

**Comment by geneguvo** [comment] 2015-11-10 13:30
From these 4GB, 1.1GB is only about json records like these:
```,{"cksum": 4127896556, "publishname": "RecoSkim2015_2015DLowPU_ReTracking_v4-6ca56d9a50b153298a3c6a7ed0fc5558", "adler32": "987b1894", "globaltag": "None", "outdataset": "/L1MinimumBiasHF1/davidlw-RecoSkim2015_2015DLowPU
_ReTracking_v4-6ca56d9a50b153298a3c6a7ed0fc5558/USER", "lfn": "/store/user/davidlw/L1MinimumBiasHF1/RecoSkim2015_2015DLowPU_ReTracking_v4/151109_223122/0000/pPb_HM_63.root", "pandajobid": 63, "filesize": 32122232, "filet
ype": "EDM", "swversion": "CMSSW_7_4_15_patch1", "state": "None", "created": "2015-11-10 00:13:36.204361", "runlumi": {"259163": ["34", "35", "51"]}, "tmplfn": "/store/user/davidlw/L1MinimumBiasHF1/RecoSkim2015_2015DLowP
U_ReTracking_v4/151109_223122/0000/pPb_HM_63.root", "parents": ["/store/data/Run2015D/L1MinimumBiasHF1/RECO/PromptReco-v4/000/259/163/00000/F6B48395-A374-E511-A4F2-02163E012561.root"], "location": "T2_US_MIT", "inevents"
: 3224, "taskname": "151109_223122:davidlw_crab_RecoSkim2015_MB_2015D_batch1_v4", "acquisitionera": "null", "tmplocation": "T2_US_MIT", "md5": "asda"}```

That is, records with "tmplfn" and ended by '''"md5": "asda"'''. So this API is probably a leaker.

**Comment by geneguvo** [comment] 2015-11-10 13:45
There's also significant number of json records with the "ASO log start ... ASO log finish" on it, like this:
```
'3324': {'State': 'failed', 'Error': [90000, u"Got fatal stageout exception:\nStageout failed with code 1.\nThere were 2 failed/killed stageout jobs. 2 of those jobs had a permanent failure.\nFailure reasons (per document) follow:\n- a27187d3c2b6e0c10df30feb728eaba47bf741ad287ee9073ad10040:\n  -----> ASO log start -----\n  ['TRANSFER  globus_ftp_client: the server responded with an error 500 Command failed. : open/create : [ERROR] Server responded with an error: [3005] Unable to get quota space - quota not defined or exhausted /eos/cms/store/user/ztu/QCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8/RECO_7iters_hiRegit_point8R_V0ProducerUPDATE_752_pt15_7000_pythia8_v7/151010_142345/0003/step3_2_3324.root; Disk quota exceeded    ']\n  <----- ASO log finish ----\n  The last failure reason is permanent.\n- b1641089adbd4ef0b8ff8b4651799267f11f35b6b06f16e3d6ae58bf:\n  -----> ASO log start -----\n  ['TRANSFER  globus_ftp_client: the server responded with an error 500 Command failed. : open/create : [ERROR] Server responded with an error: [3005] Unable to get quota space - quota not defined or exhausted /eos/cms/store/user/ztu/QCD_Pt-15to7000_TuneCUETP8M1_Flat_13TeV_pythia8/RECO_7iters_hiRegit_point8R_V0ProducerUPDATE_752_pt15_7000_pythia8_v7/151010_142345/0003/log/cmsRun_3324.log.tar.gz; Disk quota exceeded    ']\n  <----- ASO log finish ----\n  The last failure reason is permanent.", {}]}
```

So whatever is keeping track of ASO log errors seems to be also leaking.

**Comment by belforte** [comment] 2015-11-10 20:56
thanks Diego.
To make sure I understand the basics, so you mean the attached plot and do I read it correctly that crabserver has been using 30GB of RAM in last 5 days ?
![screenshot from 2015-11-10 21 53 51](https://cloud.githubusercontent.com/assets/1837785/11075511/bd2281f8-87f5-11e5-825a-fd0073266db7.png)

As to investigating and solving, I have heard from Marco that he should be at work next week, so I hope he can take care.

**Comment by geneguvo** [comment] 2015-11-11 11:34
That's actually memory percentage. So ~30% of 8GB, plus what was in the swap.

Bruno is going to change those kibana plots to show the absolute value in MBytes instead.

**Comment by mmascher** [comment] 2015-12-02 14:38
Thanks Diego, I think the coredump is going to help me debug this.

I think the two things you mentioned are respectively a filemetadata API that ASO queries to get data to perform publication (https://github.com/dmwm/CRABServer/blob/master/src/python/CRABInterface/DataFileMetadata.py#L22-L47), and a data structure returned by the status API.

I doubt the filemetadata API is the problem, it has not been touched since a lot of time, and I don't see anything that can cause a leak (unless the issue is ina new version of cx_oracle or in Lassi's REST). On the other hand the memory footprint of this API is pretty big, so I am not surprise you find a lot of this data in the dump. As a reference I counted 101 distinct tasks in this category that probably means 101 API calls. Given the low number it could be thatthis data was thre waiting to be garbage collected imho.

About the status API, the code is more complicated but I don't seem to find any reason why references are not garbage collected. I will look more into this.

**Comment by geneguvo** [comment] 2015-12-03 17:48
Hi Marco,
Might be of help: you can check what's in gc.garbage after the call as it contains stuff that will never be collected. I.e.:
```
import gc
class BigObj(object):
  def set_pointer(self, pointto):
     self.pointer = pointto

  def __del__(self):
     print "deleting %s" % self

def myfunc():
  a = BigObj()
  b = BigObj()
  a.set_pointer(b)
  b.set_pointer(a)

myfunc()
gc.collect()
print "This will never be collected:", gc.garbage
```

If you'd break the cycle (i.e do a ```b.set_pointer("something")``` instead of ```b.set_pointer(a)``` above), then you'd see things being de-allocated.

Reference: https://docs.python.org/2/library/gc.html.

**Comment by mmascher** [comment] 2015-12-14 16:56
Hi all,

I think I found out what is happening here, and to me it seems also strictly related to how python manages memory, in particular for small objects. So, let me take a digression first.

Python uses its own private heap containing all Python objects and data structures. The Python memory manager calls `free/malloc` (or whatever) to request memory to the operating system (which in turn call an API operating system related to get the memory). To avoid the overload of the operating system there is not a 1:1 map between a object going out of scope and a `free` call, but the Python memory manager keeps the memory to himself because it assumes this memory might be handy in the future. Here it is a nice link I found out that describes how this work see http://www.evanjones.ca/memoryallocator/ (well, it's a proposal for an improvement, but it's to give you an idea). I have also found this link useful http://deeplearning.net/software/theano/tutorial/python-memory-management.html

That being said, if you have, for example, a huge dictionary containing small objects, then the python interpreter will assume you will need the same amount of memory in the future and it will not free it.

In the core dump Diego provided there is a lot of data coming from a call to this API https://github.com/dmwm/CRABServer/blob/master/src/python/CRABInterface/DataFileMetadata.py#L22-L47 (e.g., this call and its variants: https://cmsweb.cern.ch/crabserver/prod/filemetadata?taskname=151210_191604:mabarrio_crab_TopTree_ZJets&filetype=POOLIN), which is exactly the pattern I mentioned above: big dictionary containing small objects.

At the end of the comment there is a script I used to simulate the behavior of this API. You can copy/paste it and do some test if you want.

I did a simulation with a task with 100 files 30 lumis each (small), a task with 1000 files and 100 lumis each (probably the average), and a big task of 10k jobs 500 lumis each. Then I printed the memory consumption before and after collecting the memory of the dictionary:

```
Memory starting the program
7540
Task with 100 files and 30 lumis
Dictionary generated and converted to string. String len is 324. Memory usage
8668
Memory usage after gc
8340
Task with 1000 files and 100 lumis
Dictionary generated and converted to string. String len is 3902. Memory usage
22440
Memory usage after gc
18280
Task with 100 files and 30 lumis
Dictionary generated and converted to string. String len is 325. Memory usage
18280
Memory usage after gc
18280
Task with 10000 files and 500 lumis
Dictionary generated and converted to string. String len is 76132. Memory usage
419172
Memory usage after gc
343036
Task with 100 files and 30 lumis
Dictionary generated and converted to string. String len is 325. Memory usage
343080
Memory usage after gc
343080
Task with 1000 files and 100 lumis
Dictionary generated and converted to string. String len is 3898. Memory usage
343080
Memory usage after gc
343080
Task with 100 files and 30 lumis
Dictionary generated and converted to string. String len is 325. Memory usage
343080
Memory usage after gc
343080
Task with 10000 files and 500 lumis
Dictionary generated and converted to string. String len is 76139. Memory usage
419196
Memory usage after gc
343056
```

As you can see a big task is loaded into memory then the memory footprint of the python process never shrink. That explains the huge quantity of `records with "tmplfn" and ended by '''"md5": "asda"'''`. I haven't analyzed the other type of data found in the coredump (the status call), but I fear it has the same issue: few parallel calls with high memory footprint (or a single big call) and then the memory allocatd by the Python memory manager is gone. I think we (I) need to concentrate on how to reduce the memory footprint of the getfiles API as a first item.

Let me know if you have comments, I'll follow up if I have some ideas.

```python
import gc
import os
import psutil
import random
import string


def randstr(size):
    """ Generate a random string of size charaters
        For example randstr(20) returns something like:
        'L2YEEREND4THO0RP4ZYA'
    """
    return ''.join(random.choice(string.ascii_uppercase + string.digits) for _ in xrange(size))


def bigdict(size):
    """ Return a big dictionary that is as similar as possible to the one used in the
        runlumi field of the filemetadata.

        Return something like:
            {'140295': ['81809',
                '56876',
                '106697',
                '141068',
                '86853',
                '59688',
                '72787',
                '102868',
                '57237']
            }
    """
    res = {}
    runnum = str(random.randint(50000, 150000))
    res[runnum] = []
    for i in xrange(1, size):
        res[runnum].append(str(random.randint(50000, 150000)))

    return res


def filemetadataDict(nfiles, lumisPerFile):
    """ Return some data as similar as possible to the filemetadata
    """
    for i in xrange(nfiles):
        yield {
            "cksum": 0,
            "publishname": randstr(random.randint(40,60)), #"TopTree_ZJets_25ns-00000000000000000000000000000000"
            "adler32": "0",
            "globaltag": "None",
            "outdataset": randstr(random.randint(70,160)), #"/FakeDataset/fakefile-FakePublish-5b6a581e4ddd41b130711a045d5fecb9/USER"
            "lfn": randstr(random.randint(150,250)),#"/store/mc/RunIISpring15MiniAODv2/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/MINIAODSIM/74X_mcRun2_asymptotic_v2-v1/60000/F6D2F58C-B170-E511-9177-002618943885.root_34"
            "pandajobid": random.randint(1,10000),
            "filesize": 0,
            "filetype": random.choice(["POOLIN","TFILE","EDM","LOG"]),
            "swversion": "CMSSW_7_4_%s" % random.randint(1,50),
            "state": "None",
            "created": randstr(30),#"2015-12-11 07:28:06.941284"
            "runlumi": bigdict(lumisPerFile),#{"1": ["68101", ... "304376"] ...}
            "tmplfn": randstr(random.randint(150,250)),#"/store/mc/RunIISpring15MiniAODv2/DYJetsToLL_M-50_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8/MINIAODSIM/74X_mcRun2_asymptotic_v2-v1/60000/F6D2F58C-B170-E511-9177-002618943885.root_34"
            "parents": [randstr(random.randint(150,250)) for _ in xrange(10,20)], #list of parents
            "location": randstr(1),#"T2_ES_CIEMAT"
            "inevents": random.randint(50000,250000),
            "taskname": randstr(random.randint(30,60)),#"151210_191604:mabarrio_crab_TopTree_ZJets"
            "acquisitionera": "null",
            "tmplocation": randstr(1),#"T2_US_Wisconsin"
            "md5": "0"
        }

def printInfo(nfiles, lumisPerFile):
    """ Print the information after creating a dict of nfiles files each
        containing lumisPerFile lumis. Print the memory info after garbage collecting the object
    """
    print "Bigdict(%s, %s)" % (nfiles, lumisPerFile)
    d = list(filemetadataDict(nfiles, lumisPerFile))
    s = str(d)
    print "string len is %s" % (len(s)/1024)
    print process.get_memory_info()[0]/1024
    d = None
    s = None
    gc.collect()
    print process.get_memory_info()[0]/1024


if __name__ == "__main__":
    process = psutil.Process(os.getpid())

    print "Memory starting the program"
    print process.get_memory_info()[0]/1024

    printInfo(100, 30) #small task
    printInfo(1000, 100) #Average case (1k jobs, 300 lumis per job) ?
    printInfo(100, 30) #small task
    printInfo(10000, 500) #Big task (10k jobs, 500 lumis per job) ?
    printInfo(100, 30)
    printInfo(1000, 100)
    printInfo(100, 30)
    printInfo(10000, 500)

**Comment by ericvaandering** [comment] 2015-12-14 17:08
@vkuznet can a generator creating a string, maybe into a bytearray help here?

**Comment by mmascher** [comment] 2015-12-14 17:11
Yes, that was my thought, any example on how to stream code from a server to a client using pycurl is welcome. I am afraid the current implementation (Lassi's REST) encodes everything into a single HTTP answer, even though the crabserver API is a generator..

**Comment by ericvaandering** [comment] 2015-12-14 17:14
But another thing that will alleviate but not solve this is why are you not using the ranged version of the bigdict? Files are going to tend to have ranges of lumis, not scattered lumis.

**Comment by mmascher** [comment] 2015-12-14 18:00
True, that's another option. Here we take the runlumi from the fjr and simply put it in the DB. We can probably compact them (on the worker node to not take a memory issue and turn it into a CPU issue :)). I would look into the "pycurl streaming first" though which solves the problem once and for all.

**Comment by vkuznet** [comment] 2015-12-14 18:03
To all, 
please read these [1] slides about python memory allocations. I extracted them from the course material I took in python mastery class, I can't release whole materials though without instructor permission. But basically, python always allocates extra memory for any container, including dict. The dicts are worse in terms of memory allocation, you'll see it from the slides. Said that, the steaming of data can be done in a different way. Instead of yielding a large dicts, you need to organize your stream as a "table". Lassi proposed compact JSON serialization in [2,3]. If you concern about your dict size, then you should consider flatten it into [2,3] format. This format will allow streaming, since you can yield just rows of data and will not required json.dump(Bigdata). The later is done for you by WMCore since you yield dictionary this dictionary is dumped by json.dump call into the wire. If you'll need assistance in writing code with new format please let me know. But I hope it would be clear from [2,3] how you can do it, e.g. first yield the "header", then yield row by row and close it with "footer". For example
yield """{"desc": {"columns": ["ABC", "DEF"]}, "result": ["""
yield """[val1, val2]"""
...
yield "]}"

This is THE reason why DAS reads Phedex data from XML APIs rather than JSON ones (Phedex also ships large nested dict which blows up DAS memory). And of course, you'll need to adjust your client to read a stream (again it should be trivial, the columns will tell you how to create a dict and then you read each row and creates appropriate data structure from your columns and data values).

[1] https://www.dropbox.com/s/kcwhvgd4xjejyx3/PythonContainers.pdf?dl=0
[2] https://hypernews.cern.ch/HyperNews/CMS/get/webInterfaces/752.html
[3] https://hypernews.cern.ch/HyperNews/CMS/get/webInterfaces/753.html

**Comment by mmascher** [comment] 2015-12-14 19:34
Hi Valentin,

thanks, that's interesting stuff, I will look into that material for the streaming for the future!

Let me stress that the issue is not only overallocation, it's really that the memory allocated is not released to the OS when the dictionary goes out of scope and is not referenced anymore. And that makes you think of a memory leak since you see the process taking up a lot of memory even when it is doing nothing.

A small really quick improvement to this problem is using `yield json.dumps(bigdict)` instead of `yield bigdict`. I have checked that at the end of the day my test script uses 7Mb of memory isntead of 340Mb (which is all unreferenced RAM kept by the python interpreter for future use). I also verified that the memory footprint is reduced to 40%

I propose we start doing this simple quick change as of February so to rule out any other issue. Streaming is cool but it seems to me a bigger development item and I am not sure I can do it for February..

**Comment by vkuznet** [comment] 2015-12-14 20:18
I obviously don't know CRAB code and can't speak for its memory allocation. But from what is shown in this issue I guess ```yield bigdict``` does not release the reference and the higher layer keep it because of client connection (possibly) or other reason. While using ```json.dumps(bigdict)``` releases the references and therefore memory is not longer required to keep around.

**Comment by ericvaandering** [comment] 2015-12-14 21:14
"We can probably compact them"

Well, IMO every time we have a list of lumis is should be in the compact form, but that's probably because I invented it way back when. :smile:

**Comment by mmascher** [comment] 2015-12-15 11:33
It's not that the reference is not released, the point is that the memory management of a list of big dictionaries is different than a list of big strings. For big strings the Python memory manager calls a `malloc/free`, for big dictionary where you have many small objects inside the dict, the Python memory manager does not call a single `malloc/free` for each single small object in the dict, but caches them and doen not release the memory when the reference count goes to 0.

**Comment by vkuznet** [comment] 2015-12-15 14:57
Marco please replace str with json.dumps, I posted comment directly to your commit.

**Comment by mmascher** [comment] 2015-12-15 15:04
I see your comment, will do it, thanks!

**Comment by belforte** [comment] 2017-02-15 18:13
long done.

**Closed by belforte** 2017-02-15 18:13 UTC
Labels: old/to review
