### ISSUE TITLE
task in transition mode will give failure

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#5003] opened 2015-09-22 18:44 UTC
See https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/954/1.html 
So to get this error, need to do a lot of crab status when just submitted a task, and try to get this failure https://github.com/dmwm/CRABServer/blob/master/src/python/CRABInterface/HTCondorDataWorkflow.py#L413-L418

Also check what taskStatusCode, but I guess it will be 5 when it is in transition mode.

**Comment by AndresTanasijczuk** [comment] 2015-09-22 18:55
Besides that fact that it should give a failure, one trivial thing to change is to skip the " Hold reason: "  message if DagmanHoldReason is None.

**Comment by AndresTanasijczuk** [comment] 2015-09-22 19:10
With the new status code, the task status I think will not be anymore UNKNOWN, but whatever is in the TaskDB. Can you maybe use this to avoid adding the failure message in the lines you pointed? I mean, something like:
```
if not (result['status'] == '<in transition>' and DagmanHoldReason == None):
   add failure message
```

**Comment by belforte** [comment] 2015-09-22 21:28
what does it mean "time when task is in transition mode from idle -> running" ???
aren't task status changes atomic ?

so far I swallowed UNKNOWN as "status query to schedd failed, so CrabServer can't
get an up to date status" and already do not like it. Now... what is this ?

**Comment by belforte** [comment] 2017-02-14 10:18
now is a duplicate of #5323

**Closed by belforte** 2017-02-14 10:18 UTC
