### ISSUE TITLE
"You cannot resubmit/kill jobs if the task is in status HOLDING" should not result in error 500

### ISSUE THREAD

**Issue by mapellidario** [dmwm/CRABServer#7163] opened 2022-03-22 08:25 UTC
I noticed a small increase in HTTP error 500 this morning. One of them looked like [1], "'You cannot resubmit jobs if the task is in status HOLDING". I would return an error 403 in this case [2]

If we already have an issue about this, I did not found it, I am sorry! In case, feel free to close this!

[1]

```plaintext
[22/Mar/2022:08:32:51]  RESTSQL:gEeQtRdhUGav disconnecting - Podname=crabserver-6d46f946bb-6jsng
[22/Mar/2022:08:32:51]  SERVER REST ERROR WMCore.REST.Error.ExecutionError 690a1731992a0ba021939e076878a545 (Execution error) - Podname=crabserver-6d46f946bb-6jsng
[22/Mar/2022:08:32:51]    Traceback (most recent call last): - Podname=crabserver-6d46f946bb-6jsng
[22/Mar/2022:08:32:51]      File "/data/srv/HG2202e-b2671ebb11b2d65381339dff01177eb8/sw.crab_python3/slc7_amd64_gcc630/cms/crabserver/py3.220218-128bd804c35d83c081c2a5e5
9441f52b/lib/python3.8/site-packages/WMCore/REST/Server.py", line 728, in default - Podname=crabserver-6d46f946bb-6jsng
[22/Mar/2022:08:32:51]        return self._call(RESTArgs(list(args), kwargs)) - Podname=crabserver-6d46f946bb-6jsng
[22/Mar/2022:08:32:51]      File "/data/srv/HG2202e-b2671ebb11b2d65381339dff01177eb8/sw.crab_python3/slc7_amd64_gcc630/cms/crabserver/py3.220218-128bd804c35d83c081c2a5e5
9441f52b/lib/python3.8/site-packages/WMCore/REST/Server.py", line 809, in _call - Podname=crabserver-6d46f946bb-6jsng
[22/Mar/2022:08:32:51]        obj = apiobj['call'](*safe.args, **safe.kwargs) - Podname=crabserver-6d46f946bb-6jsng
[22/Mar/2022:08:32:51]      File "/data/srv/HG2202e-b2671ebb11b2d65381339dff01177eb8/sw.crab_python3/slc7_amd64_gcc630/cms/crabserver/py3.220218-128bd804c35d83c081c2a5e5
9441f52b/lib/python3.8/site-packages/WMCore/REST/Server.py", line 1776, in dbapi_wrapper - Podname=crabserver-6d46f946bb-6jsng
[22/Mar/2022:08:32:51]        self._dberror(e, format_exc(), False) - Podname=crabserver-6d46f946bb-6jsng
[22/Mar/2022:08:32:51]      File "/data/srv/HG2202e-b2671ebb11b2d65381339dff01177eb8/sw.crab_python3/slc7_amd64_gcc630/cms/crabserver/py3.220218-128bd804c35d83c081c2a5e5
9441f52b/lib/python3.8/site-packages/WMCore/REST/Server.py", line 1774, in dbapi_wrapper - Podname=crabserver-6d46f946bb-6jsng
[22/Mar/2022:08:32:51]        return handler(*xargs, **xkwargs) - Podname=crabserver-6d46f946bb-6jsng
[22/Mar/2022:08:32:51]      File "/data/srv/HG2202e-b2671ebb11b2d65381339dff01177eb8/sw.crab_python3/slc7_amd64_gcc630/cms/crabserver/py3.220218-128bd804c35d83c081c2a5e5
9441f52b/lib/python3.8/site-packages/CRABInterface/RESTUserWorkflow.py", line 661, in post - Podname=crabserver-6d46f946bb-6jsng
[22/Mar/2022:08:32:51]        return self.userworkflowmgr.resubmit2(workflow=workflow, - Podname=crabserver-6d46f946bb-6jsng
[22/Mar/2022:08:32:51]      File "/data/srv/HG2202e-b2671ebb11b2d65381339dff01177eb8/sw.crab_python3/slc7_amd64_gcc630/cms/crabserver/py3.220218-128bd804c35d83c081c2a5e5
9441f52b/lib/python3.8/site-packages/CRABInterface/DataUserWorkflow.py", line 157, in resubmit2 - Podname=crabserver-6d46f946bb-6jsng
[22/Mar/2022:08:32:51]        return self.workflow.resubmit2(workflow, publication, jobids, siteblacklist, sitewhitelist, maxjobruntime, maxmemory, numcores, priority) -
 Podname=crabserver-6d46f946bb-6jsng
[22/Mar/2022:08:32:51]      File "/data/srv/HG2202e-b2671ebb11b2d65381339dff01177eb8/sw.crab_python3/slc7_amd64_gcc630/cms/crabserver/py3.220218-128bd804c35d83c081c2a5e59441f52b/lib/python3.8/site-packages/CRABInterface/Utilities.py", line 179, in wrapped_func - Podname=crabserver-6d46f946bb-6jsng
[22/Mar/2022:08:32:51]        return func(*args, **kwargs) - Podname=crabserver-6d46f946bb-6jsng
[22/Mar/2022:08:32:51]      File "/data/srv/HG2202e-b2671ebb11b2d65381339dff01177eb8/sw.crab_python3/slc7_amd64_gcc630/cms/crabserver/py3.220218-128bd804c35d83c081c2a5e59441f52b/lib/python3.8/site-packages/CRABInterface/DataWorkflow.py", line 296, in resubmit2 - Podname=crabserver-6d46f946bb-6jsng
[22/Mar/2022:08:32:51]        raise ExecutionError(msg) - Podname=crabserver-6d46f946bb-6jsng
[22/Mar/2022:08:32:51]    WMCore.REST.Error.ExecutionError: ExecutionError 690a1731992a0ba021939e076878a545 [HTTP 500, APP 403, MSG 'Execution error', INFO 'You cannot resubmit jobs if the task is in status HOLDING.', ERR None] - Podname=crabserver-6d46f946bb-6jsng
[22/Mar/2022:08:32:51] crabserver-6d46f946bb-6jsng 137.138.63.135 "POST /crabserver/prod/workflow HTTP/1.1" 500 Internal Server Error [data: 7235 in 745 out 38163 us ] [auth: OK "/DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=chenguan/CN=832904/CN=Chenguang Zhang" "" ] [ref: "" "CRABClient/v3.220210" ] - Podname=crabserver-6d46f946bb-6jsng
[22/Mar/2022:08:32:51]  RESTSQL:gEeQtRdhUGav DISCONNECTED cms_analysis_reqmgr_w@cmsr timeout=300 inuse=0 idle=1 - Podname=crabserver-6d46f946bb-6jsng
```

[2] from [wikipedia](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes), 403 Forbidden

> The request contained valid data and was understood by the server, but the server is refusing action. This may be due to the user not having the necessary permissions for a resource or needing an account of some sort, or attempting a prohibited action (e.g. creating a duplicate record where only one is allowed). This code is also typically used if the request provided authentication by answering the WWW-Authenticate header field challenge, but the server did not accept that authentication. The request should not be repeated.

**Comment by belforte** [comment] 2022-03-22 08:31
duplicate of https://github.com/dmwm/CRABServer/issues/7062

**Closed by belforte** 2022-03-22 08:31 UTC
Labels: Type: Enhancement
